return PlaceObj('ModDef', {
	'title', "Enemies Evolve!",
	'description', 'Credits go to https://steamcommunity.com/id/ivangr Mnementh who created the original implementation of the mod below.\nhttps://steamcommunity.com/sharedfiles/filedetails/?id=3010501248&searchtext=level+up\n\n[h1]Tired of fighting 200-500 stupidly weak units in each attack wave?[/h1]\nTired of building and using only the aoe weapons/defenses?\n[i]Do you want to feel like your base is actually under threat?[/i]\n\nYou came to the right place!\n\n[h2][b]This mod adds distinct "Evolutions" to 8 of the major animal species so that each genus has 5 tiers of upgrades![/b][/h2]\n[h2]The Robotic enemies from the Hope DLC have also been overhauled and expanded![/h2]\n\nIf the game realizes it would send more units in an attack wave, higher than a mod setting, it will upgrade a unit selected in the attack to be upgraded.\n[i]For example:[/i]\nA 160 Skarabei attack becomes an 80 Poisonous Skarabei attack.\nThis mod keep re-checking and upgrading until an attack is under your desired amount.\n\nSpecial notes:\n1. Base species or Robot "class" is respected. \n1a. Skarabei attacks will always be Skarabei\n\n2. On the highest difficulties, multi-year run will our of upgrades. \nIf that happens, the game will still upgrade. And instead of 400 paltry Skarabei you will be eventually attacked by 400 Final Form Skarabei.\nGood luck keeping your base in this circumstance! ¯\\_(:D)_/¯\n\n[h1]Each tier is exponentially more difficult to deal with!/[/h1]\n[h2]Final Forms are base killers! They are not intended to fight fair! [/h2]\n\n[b]Each upgrade should feel close to the jump in difficulty from fightning a Shrieker Hatchling to a Shrieker Broodmother[/b]\n\n[h3]By default EVERY upgrade grants 2x health & 2x pain tolerance.[/h3]\nTHEN species specific upgrade(s) get applied.\nAka Skarabei will gain +10% pierce armour(As they are evolving to be highly resistant to arrows/bullets)\nHave fun discovering how each species is evolving to better defeat you!\n\n[h3]The following species have upgrade paths:[/h3]\n- Juno\n- Shriekers\n- Scissorhands\n- Tecatli\n- Dragonfly\n- Glutch\n- Skarabei\n- Noth\n- Ulfen\n- Shogu\n- Dromadda\n- Draka\n\nThe following Robot "species" also have valid upgrade paths:\n- Light Assault\n- Heavy Assault\n- Demolitionist\n- Scout\n- Armored Forge Crawler\n- Crawler Cannons\n\nAs new enemy tiers are found, they will require re-observing.\nThis gives you more vignettes into your colony.... but maybe more importantly and it will give you more details about strengths and weaknesses!\n\n[h1]Did I mention a Combat Overhaul?!?[/h1]\nThe base Stranded Alien Dawn only gave animals piercing/blunt damage.\nAnd most weapons dealt piercing or energy damage\nNo longer!\nEach animal now deals 1 - 2 damage types\nAnd when observed, you are clearly told what damage they deal.\n- Scissorhands/Gujo deal pure Piercing\n- Juno deal pure Blunt\n- Glutch deal pure Gas\n- Dragonly deal pure Energy\n- Tecatli\'s deal Energy/Gas\n- Skarabei now deal Blunt/Gas damage\n- Shriekers now deal Blunt/Pierce\n- Dogs deal Piercing/Energy\n\n[h2]Armor Rework![/h2]\nSo enemies are scarier, am I giving you anything to handle this increase?\nAll base game armor now gives larger defenses bonuses.\nWith 2 options "Complex" or "Simple"\n\nComplex bonuses are as follows:\n- [b]Leather[/b] has great Energy resistance \n- [b]Veggie Leather[/b] generally improves from base Leather\n- [b]Synethic[/b] has great Pierce resistance\n- [b]Carbon[/b] has great Blunt resistance\n- [b]Improved Carbon[/b] is meant to be second best against everything\n\nSimple bonuses grant a flat deflection % to each category.\nWith the tier of the armor determining the #:\nLeather < Veggie Leather < Synthetic < Carbon < Improved Carbon\n\nYou can now get 75% deflection chance through either method.\n\n[h1]Not satisfied or entertained? How about a Taming rework as well![/h1]\nAll animal upgrades are Tame-able!\n[i]However[/i] each evolution grants pacification defense and lowers the chance to tame.\n\nSo how do you get one of these mega-beasts?\nWell heavy continuous pacification weaponry fire\nOR you can tame a lower evolution\'s mating pair.\nJuno, Shrieker, Scissorhands, Tecatli, Gujo\'s, Noth\'s, Shogu\'s, Draka\'s, Dromaddas, & Dogs now:\n- Have offspring of the next evolution\n- Eat less food per day (Final Forms eat the same as base game counterparts)\n- Have at least a 9x increased chance to become pregnant (And grow that much faster from a child)\n- Immediately Draftable / spawn with Training lvl 5 \n(Although more training is recommended)\n- Tecatli & Dogs are inherently more difficult to train/breed\n\n[h3]But tames are bad?!? Why should I use them?[/h3]\nWhen the game attacks you, it [b]does not[/b] consider how many tames you have.\nSo a colony with no tames (But static defenses) vs a colony with the same defenses with 50 Final Form Shriekers defending get the same attack!\n\nSo Tames are cheaper, quicker to grow and use in combat, and "[b]Free[/b]"\n\nThere are some enemies that do not care about Flamethrowers or missile AoE attacks. Making flamethrowers and AoE less desirable.\n\nAll this is meant to make it a tougher decision to avoid taming and using a large army of beasts to help your fledgling colony!\n\nSeee here for this mods git; where you can review pending content and open bugs.\nhttps://github.com/757Bkob/SAD_ILU\n\nIf you are still reading, a quick [i]compatibility disclaimer[/i].\nThis mod is a combat overhaul mod; and any other mods that add animals/equipments/weapons (Or edit the base game items) should be scrutinized before used with this mod.\nI am not opposed to integrating other mods to ensure compatibility, and I will do them as requested.',
	'last_changes', "4.6.4.3\n\n1 Under the hood change: All Robots used in teh nest mod have had the unitcomponent UntiNesting added to them, so I do not need to rely on a reimplementation of UnitNesting specifically for Robots.\n\nPlease see the git in the mod description for open bugs, and even submit your own\nFeedback is always welcome to fine tune the balance of things!",
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "sad_commonlib",
			'title', "SAD_CommonLib",
			'version_major', 1,
			'version_minor', 12,
		}),
	},
	'id', "rtw6tLg",
	'author', "Ark Builder",
	'version_major', 4,
	'version_minor', 6,
	'version', 170,
	'lua_revision', 233360,
	'saved_with_revision', 373414,
	'entities', {
		"OutdoorCrafting",
	},
	'code', {
		"Code/SpecialFuelClass.lua",
		"Code/upgradeCall.lua",
		"Building/Turret_ToxicGun.lua",
		"Robot/LightHostileRobot_LVL1.lua",
		"Robot/LightHostileRobot_LVL2.lua",
		"Robot/LightHostileRobot_LVL3.lua",
		"Robot/LightHostileRobot_LVL4.lua",
		"Robot/LightHostileRobot_LVL5.lua",
		"Robot/HostileRobot_Scout_LVL1.lua",
		"Robot/HostileRobot_Scout_LVL2.lua",
		"Robot/HostileRobot_Scout_LVL3.lua",
		"Robot/HostileRobot_Scout_LVL4.lua",
		"Robot/HostileRobot_Scout_LVL5.lua",
		"Robot/HostileRobot_Monk_LVL1.lua",
		"Robot/HostileRobot_Monk_LVL2.lua",
		"Robot/HostileRobot_Monk_LVL3.lua",
		"Robot/HostileRobot_Monk_LVL4.lua",
		"Robot/HostileRobot_Monk_LVL5.lua",
		"Robot/HeavyHostileRobot_LVL1.lua",
		"Robot/HeavyHostileRobot_LVL2.lua",
		"Robot/HeavyHostileRobot_LVL3.lua",
		"Robot/HeavyHostileRobot_LVL4.lua",
		"Robot/HeavyHostileRobot_LVL5.lua",
		"Robot/Crawl_Cannon_T0.lua",
		"Robot/Crawl_Cannon_T1.lua",
		"Robot/Crawl_Cannon_T2.lua",
		"Robot/Crawl_Cannon_T3.lua",
		"Robot/Crawl_APC_LVL1.lua",
		"Robot/Crawl_APC_LVL2.lua",
		"Robot/Crawl_APC_LVL3.lua",
		"Robot/HostileCombatQuadcopter_LVL2.lua",
		"Robot/HostileCombatQuadcopter_LVL3.lua",
		"Robot/HostileCombatQuadcopter_LVL4.lua",
		"Robot/HostileCombatQuadcopter_LVL5.lua",
		"Robot/Demo_1.lua",
		"Robot/Demo_2.lua",
		"Robot/Demo_3.lua",
		"Robot/Demo_4.lua",
		"Robot/Demo_5.lua",
		"UnitAnimal/GujoT5.lua",
		"UnitAnimal/GujoT4.lua",
		"UnitAnimal/GujoT3.lua",
		"UnitAnimal/GujoT2.lua",
		"UnitAnimal/Gujo.lua",
		"UnitAnimal/dog_T5.lua",
		"UnitAnimal/dog_T4.lua",
		"UnitAnimal/dog_T3.lua",
		"UnitAnimal/dog_T1.lua",
		"UnitAnimal/Heavily_Mutated_PEx_Skarabei_Brute.lua",
		"UnitAnimal/Mutated_PEx_Skarabei_Brute.lua",
		"UnitAnimal/PEx_Skarabei_Brute.lua",
		"UnitAnimal/PEx_Skarabei.lua",
		"UnitAnimal/BadTrip_Bloated_Glutch_Stitcher.lua",
		"UnitAnimal/BadTrip_Bloated_Glutch.lua",
		"UnitAnimal/Bloated_Glutch.lua",
		"UnitAnimal/Glutch_Stitcher.lua",
		"UnitAnimal/Fast_Frenzied_Fortified_Bomber_Dragonfly.lua",
		"UnitAnimal/Frenzied_Fortified_Bomber_Dragonfly.lua",
		"UnitAnimal/Frenzied_Bomber_Dragonfly.lua",
		"UnitAnimal/Frenzied_Dragonfly.lua",
		"UnitAnimal/Spellsword_Tecatli.lua",
		"UnitAnimal/Intelligent_Tecatli.lua",
		"UnitAnimal/Heat_Reinforced_Tecatli.lua",
		"UnitAnimal/Entombed_Tecatli.lua",
		"UnitAnimal/Tecatli.lua",
		"UnitAnimal/VenomousRaptors.lua",
		"UnitAnimal/Rage_Focused_Scissorhands.lua",
		"UnitAnimal/Rage_Fueled_Scissorhand_Duelist.lua",
		"UnitAnimal/Brutal_Duelist_Scissorhands.lua",
		"UnitAnimal/Scissorhands_Brute.lua",
		"UnitAnimal/Scissorhands_Brute_Nesting.lua",
		"UnitAnimal/Scissorhands.lua",
		"UnitAnimal/Scissorhands_Nesting.lua",
		"UnitAnimal/Junoskar.lua",
		"UnitAnimal/Too_Angry_Too_Die_Juno.lua",
		"UnitAnimal/Hulk_Juno.lua",
		"UnitAnimal/Angry_Juno.lua",
		"UnitAnimal/Juno_Brute.lua",
		"UnitAnimal/Juno.lua",
		"UnitAnimal/Sniping_Entropy_Shielded_Shrieker.lua",
		"UnitAnimal/Plague_Sniper_Shrieker.lua",
		"UnitAnimal/Entropic_Shrieker.lua",
		"UnitAnimal/Shrieker_Manhunting.lua",
		"UnitAnimal/Shrieker_Manhunting_Mother.lua",
		"UnitAnimal/Shrieker_Mother.lua",
		"UnitAnimal/Ulfen.lua",
		"UnitAnimal/Ulfen_T2.lua",
		"UnitAnimal/Ulfen_T3.lua",
		"UnitAnimal/Ulfen_T4.lua",
		"UnitAnimal/Ulfen_T5.lua",
		"UnitAnimal/Noth.lua",
		"UnitAnimal/Noth_T2.lua",
		"UnitAnimal/Noth_T3.lua",
		"UnitAnimal/Noth_T4.lua",
		"UnitAnimal/Noth_T5.lua",
		"UnitAnimal/Draka.lua",
		"UnitAnimal/Draka_T2.lua",
		"UnitAnimal/Draka_T3.lua",
		"UnitAnimal/Draka_T4.lua",
		"UnitAnimal/Draka_T5.lua",
		"UnitAnimal/Shogu.lua",
		"UnitAnimal/Shogu_T2.lua",
		"UnitAnimal/Shogu_T3.lua",
		"UnitAnimal/Shogu_T4.lua",
		"UnitAnimal/Shogu_T5.lua",
		"UnitAnimal/Camel.lua",
		"UnitAnimal/Camel_T2.lua",
		"UnitAnimal/Camel_T3.lua",
		"UnitAnimal/Camel_T4.lua",
		"UnitAnimal/Camel_T5.lua",
		"Building/Tame_crafting.lua",
		"Entities/OutdoorCrafting.lua",
	},
	'has_options', true,
	'has_data', true,
	'saved', 1764251980,
	'code_hash', -4515108801927698822,
	'steam_id', "3350915173",
	'TagAnimals', true,
	'TagGameplay', true,
	'TagOther', true,
})