return PlaceObj('ModDef', {
	'title', "Enemies Evolve!",
	'description', "Credits go to https://steamcommunity.com/id/ivangr Mnementh who created the original implementation of the mod below.\nhttps://steamcommunity.com/sharedfiles/filedetails/?id=3010501248&searchtext=level+up\n\n[h1]Tired of fighting 200-500 stupidly weak units in each attack wave?[/h1]\nTired of building only the aoe weapons/defenses?\n[i]Do you want to feel like your base is actually under threat?[/i]\n\nYou came to the right place!\n\n[h2][b]This mod:[/b][/h2]\n[h3]1. Adds five unique evolutions to all enemy animals that massively increases each individual animals threat![/h3]\n[h3]2. Gives a blanket buff to taming animals, for defensive purposes (Which includes those new evolutions)[/h3]\n[h3]3. Expands the Robotic enemies from the Hope DLC.[/h3]\n[h3]4. Makes damage typing in enemies/weapons matter more.[/h3]\n[h3]5. Makes high difficulty games be... actually difficult.[/h3]\n\n[h2]1. Unique Evolutions![/h2]\nThis mods adds distinct evolutions and custom Lua coding when the game attacks you.\nThey work together so that the examples below happen.\n[i]Example 1:[/i]\nThe game thinks you deserve a 160 Skarabei attack wave.\nThis mod realizes that is more than 150, and evolves all the Skarabei units into Poisonous Skarabei.\nBecause Poisonous Skarabei are stronger, the game only thinks you deserve 80 if them.\n\n[i]Example 2:[/i]\nThe game thinks you deserve a 1000 Skarabei attack wave.\n(This can occur on high difficulty/moon games)\nThis mod realizes that is more than 150, and evolves the Skarabei into Poisonous Skarabei.\nBecause they are stronger, the game only thinks you deserve 620 of them.\nThis mod [i]again[/i] realizes that's more than 150, and evolves them again (and again, and again if needed)\n\nThis mod will evolve until the # of units in the attack wave stay under 150 by default.\n[i]But you can set the max # allowed in an attack wave based on what you think your PC can handle[/i]\n\nSpecial notes:\nNote #1. The base unit/species will always be respected.\nIf the game thinks you deserve a Skarabei attack, you will only get Skarabei.\nThis mod does not evolve Skarabei into Juno, or any other variation.\n\nNote #2. Each evolution is the same strength jump from a Shrieker Hatchling to a Shrieker Broodmother.\nTier 5/6 units are intended to be unfair and base killers.\n[b]They are intnded to be base killers, and I have no qualms making higher tiers that are even more unfair.[/b]\n\n[h2]2. Taming Buffs![/h2]\nTamed animals have:\n1. Eat less food per day\n1. Have higher pregnancy chances\n2. Lower gestation periods\n3. Give birth to their evolutions\n4. Will only breed to a species specific cap.\n5. Be immediatly draftable with combat lvl 5 \n(training can still be done to improve their prowess)\n\nThis cap can be hard set via mod options, or based on the max attack size set.\n\n[h2]3. The consortium strikes back[/h2]\nInstead of just light/heavy bipedal and machine gun/laser crawlers, the Consortium has undergone a massive military overhaul.\nThere are now 8 unique classes, with each having 5 evolution tiers!\nThose classes are scout, light assault, heavy assault, demo, forge, artillery, sprayer, & monk.\n\n[b]These classes are highly synergistic, and require a strategic response.[/b]\nDo you target the Scout class first because they grants buffs to all robots that attack their target.\nOr the mobile forges who increase enemy robot's armor?\nThat will leave you open to the constant barrage fire of their artillery pieces though....\n\n[h2]4. Damage Types and planning matter.[/h2]\nAs enemies (Robot and Animal) evolve, their weapons and armor get more and more unique.\nSkarabei will become near impenetrable to blunt & piercing weapons....\nGlutches will smother their targets in gaseous fumes.\n\n[i]And the normal weapons/armor need a revamping to account for this.[/i]\nThe base game armors will now provide great protection against a specific damage type.\nWith enhanced carbon providing the best general defense.\n\nThis controversial armor editing can be disabled via a mod option, and all armors will give flat all defense stats based on their armor \"tier\".\n\nWhat weapons and turrents also matter more, as equipping all your colonists with railguns will lead to bad time against a high tier Skarabei wave.\n\n[h2]Diffulty Matter[/h2]\nIn general, this will raise the difficulty of your game.\nAnd intends to shakeup the normal \"Build a blast zone gap in the walls, and fill it with missiles/flamethrowers\".\n\nI'm trying to provide a natural end game threat to colonies.\nSo players who like to just survive can feel challenged after getting their base up and running.\n\nAnd give some tools for players to respond approprietly to this increase in diffulty.\nThe above is my goal for this mod, and I plan to continue supporting it for the moderate-future.\n\n\n[h1]Links and misc stuff![/h1]\n\nWhen you find bugs in this mod (Or if you find this mod does not live up to its goals), you are more than welcome to:\n1. Comment on the steam works\n2. Comment on the Nexus Mods item\n3. Open a Git issue at: [url=https://github.com/757Bkob/SAD_EE]Enemies Evolve git link[/url]\n\nIf you want to translate this mod into another language, I am working to extract all my mods into this [url=https://docs.google.com/spreadsheets/d/1ETvz1lXC7nTnz8EYA3_NCHBmFeGaVeBHGVz_vkvTvOs/edit?usp=sharing]google sheet[/url].\n(And include what version it was extracted from)\n(Note EE currently is having \"difficulties\" exporting it's translation tables, so it is not there yet (tm))\n\n[i]A compatibility disclaimer[/i]\nThis mod is a combat & enemy overhaul mod.\nI cannot garuntee thsi mod will play nice with other mods that add animals/equipments/weapons (Or edit the base game items/code).\nAs I learn of mods, I will do my best to make sure they play nice.\nOther mods I have incorporated or made explicitly compatible:\n[url=https://steamcommunity.com/sharedfiles/filedetails/?id=3010501248]Mnementh's original Evolution mod[/url]\n- This mod was the original inspiration for this, taking their mod to it's logical conclusion.\n[url=https://steamcommunity.com/sharedfiles/filedetails/?id=3003560863]Mnementh's Pregnancy quota[/url]\n- This mod's feature is incorporated into EE via the mod option described in #2.\n- It should not be used with EE, as the evolutions make quotas.... much harder to track via the way the pregnancy quota mod does it.\n[url=https://steamcommunity.com/sharedfiles/filedetails/?id=3062496809]LukeH's Gujo Egg Mod[/url]\n- All Gujo evolutions can generate eggs\n[url=https://steamcommunity.com/sharedfiles/filedetails/?id=3047215098]LukeH's Milking Mod[/url]\n- All Ulfen, Camel, & Noth evolutions can generate milk",
	'image', "Mod/rtw6tLg/Images/New Creatures (1).png",
	'last_changes', "5.4.2 Bugfix and minor tweaks (Hotfix A):\n\nA1. Bugfix: Fixed bug where animals without evo chains where being if they where Gujo.\nIt is cleaned & shielded now.\n\n1. Content/Qol: Story popups warning the player of Gujo's turning aggressive have been added.\nGujo's turning aggressive are now also gated behind the final storybit triggering (And a small delay for last minute prep)\n\n2. Animal Buff: Higher Tier Draka Evolutions now grant minor amount of Energy Crystals\n\n3. Bugfix: Nests now have the same combat group as their units.\nI moved code that \"The Nests Awaken\" had to align combat groups down to this mod.\n\nPlease see the git in the mod description for open bugs, and even submit your own\nFeedback is always welcome to fine tune the balance of things!",
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "sad_commonlib",
			'title', "SAD_CommonLib",
			'version_major', 1,
			'version_minor', 12,
		}),
	},
	'id', "rtw6tLg",
	'author', "Ark Builder",
	'version_major', 5,
	'version_minor', 3,
	'version', 264,
	'lua_revision', 233360,
	'saved_with_revision', 373414,
	'code', {
		"Code/SpecialFuelClass.lua",
		"Code/upgradeCall.lua",
		"Code/overrides.lua",
		"Building/Turret_ToxicGun.lua",
		"Robot/LightHostileRobot_LVL1.lua",
		"Robot/LightHostileRobot_LVL2.lua",
		"Robot/LightHostileRobot_LVL3.lua",
		"Robot/LightHostileRobot_LVL4.lua",
		"Robot/LightHostileRobot_LVL5.lua",
		"Robot/HostileRobot_Scout_LVL1.lua",
		"Robot/HostileRobot_Scout_LVL2.lua",
		"Robot/HostileRobot_Scout_LVL3.lua",
		"Robot/HostileRobot_Scout_LVL4.lua",
		"Robot/HostileRobot_Scout_LVL5.lua",
		"Robot/HostileRobot_Monk_LVL1.lua",
		"Robot/HostileRobot_Monk_LVL2.lua",
		"Robot/HostileRobot_Monk_LVL3.lua",
		"Robot/HostileRobot_Monk_LVL4.lua",
		"Robot/HostileRobot_Monk_LVL5.lua",
		"Robot/HeavyHostileRobot_LVL1.lua",
		"Robot/HeavyHostileRobot_LVL2.lua",
		"Robot/HeavyHostileRobot_LVL3.lua",
		"Robot/HeavyHostileRobot_LVL4.lua",
		"Robot/HeavyHostileRobot_LVL5.lua",
		"Robot/Crawl_Cannon_T0.lua",
		"Robot/Crawl_Cannon_T1.lua",
		"Robot/Crawl_Cannon_T2.lua",
		"Robot/Crawl_Cannon_T3.lua",
		"Robot/Crawl_APC_LVL1.lua",
		"Robot/Crawl_APC_LVL2.lua",
		"Robot/Crawl_APC_LVL3.lua",
		"Robot/HostileCombatQuadcopter_LVL2.lua",
		"Robot/HostileCombatQuadcopter_LVL3.lua",
		"Robot/HostileCombatQuadcopter_LVL4.lua",
		"Robot/HostileCombatQuadcopter_LVL5.lua",
		"Robot/Demo_1.lua",
		"Robot/Demo_2.lua",
		"Robot/Demo_3.lua",
		"Robot/Demo_4.lua",
		"Robot/Demo_5.lua",
		"UnitAnimal/Gujo_T5.lua",
		"UnitAnimal/Gujo_T4.lua",
		"UnitAnimal/Gujo_T3.lua",
		"UnitAnimal/Gujo_T2.lua",
		"UnitAnimal/Gujo.lua",
		"UnitAnimal/Dog_T2.lua",
		"UnitAnimal/Scarab_T5.lua",
		"UnitAnimal/Scarab_T4.lua",
		"UnitAnimal/Scarab_T3.lua",
		"UnitAnimal/Glutch_T5.lua",
		"UnitAnimal/Glutch_T4.lua",
		"UnitAnimal/Glutch_T3.lua",
		"UnitAnimal/Glutch_T2.lua",
		"UnitAnimal/Dragonfly_T5.lua",
		"UnitAnimal/Dragonfly_T4.lua",
		"UnitAnimal/Dragonfly_T3.lua",
		"UnitAnimal/Dragonfly_T2.lua",
		"UnitAnimal/Dragonfly.lua",
		"UnitAnimal/Tecatli_T5.lua",
		"UnitAnimal/Tecatli_T4.lua",
		"UnitAnimal/Tecatli_T3.lua",
		"UnitAnimal/Tecatli_T2.lua",
		"UnitAnimal/Tecatli.lua",
		"UnitAnimal/Tecatli_T1_venom.lua",
		"UnitAnimal/Scissorhands_T5.lua",
		"UnitAnimal/Scissorhands_T4.lua",
		"UnitAnimal/Scissorhands_T3.lua",
		"UnitAnimal/Scissorhands_Brute.lua",
		"UnitAnimal/Scissorhands_Brute_Nesting.lua",
		"UnitAnimal/Scissorhands.lua",
		"UnitAnimal/Scissorhands_Nesting.lua",
		"UnitAnimal/Juno_T6.lua",
		"UnitAnimal/Juno_T5.lua",
		"UnitAnimal/Juno_T4.lua",
		"UnitAnimal/Juno_T3.lua",
		"UnitAnimal/Juno_Brute.lua",
		"UnitAnimal/Juno.lua",
		"UnitAnimal/Shrieker_T5.lua",
		"UnitAnimal/Shrieker_T4.lua",
		"UnitAnimal/Shrieker_T3.lua",
		"UnitAnimal/Shrieker_Manhunting_Mother.lua",
		"UnitAnimal/Shrieker_Mother.lua",
		"UnitAnimal/Shrieker.lua",
		"UnitAnimal/Ulfen.lua",
		"UnitAnimal/Ulfen_T2.lua",
		"UnitAnimal/Ulfen_T3.lua",
		"UnitAnimal/Ulfen_T4.lua",
		"UnitAnimal/Ulfen_T5.lua",
		"UnitAnimal/Noth.lua",
		"UnitAnimal/Noth_T2.lua",
		"UnitAnimal/Noth_T3.lua",
		"UnitAnimal/Noth_T4.lua",
		"UnitAnimal/Noth_T5.lua",
		"UnitAnimal/Draka.lua",
		"UnitAnimal/Draka_T2.lua",
		"UnitAnimal/Draka_T3.lua",
		"UnitAnimal/Draka_T4.lua",
		"UnitAnimal/Draka_T5.lua",
		"UnitAnimal/Shogu.lua",
		"UnitAnimal/Shogu_T2.lua",
		"UnitAnimal/Shogu_T3.lua",
		"UnitAnimal/Shogu_T4.lua",
		"UnitAnimal/Shogu_T5.lua",
		"UnitAnimal/Camel.lua",
		"UnitAnimal/Camel_T2.lua",
		"UnitAnimal/Camel_T3.lua",
		"UnitAnimal/Camel_T4.lua",
		"UnitAnimal/Camel_T5.lua",
		"UnitAnimal/dog_T1.lua",
		"UnitAnimal/dog_T3.lua",
		"UnitAnimal/dog_T4.lua",
		"UnitAnimal/dog_T5.lua",
		"UnitAnimal/Entropic_Shrieker.lua",
		"UnitAnimal/Sniping_Entropy_Shielded_Shrieker.lua",
		"UnitAnimal/Plague_Sniper_Shrieker.lua",
		"UnitAnimal/Angry_Juno.lua",
		"UnitAnimal/Hulk_Juno.lua",
		"UnitAnimal/Too_Angry_Too_Die_Juno.lua",
		"UnitAnimal/Junoskar.lua",
		"UnitAnimal/Brutal_Duelist_Scissorhands.lua",
		"UnitAnimal/Rage_Fueled_Scissorhand_Duelist.lua",
		"UnitAnimal/Rage_Focused_Scissorhands.lua",
		"UnitAnimal/VenomousRaptors.lua",
		"UnitAnimal/Entombed_Tecatli.lua",
		"UnitAnimal/Heat_Reinforced_Tecatli.lua",
		"UnitAnimal/Intelligent_Tecatli.lua",
		"UnitAnimal/Spellsword_Tecatli.lua",
		"UnitAnimal/Frenzied_Dragonfly.lua",
		"UnitAnimal/Frenzied_Bomber_Dragonfly.lua",
		"UnitAnimal/Frenzied_Fortified_Bomber_Dragonfly.lua",
		"UnitAnimal/Fast_Frenzied_Fortified_Bomber_Dragonfly.lua",
		"UnitAnimal/Glutch_Stitcher.lua",
		"UnitAnimal/Bloated_Glutch.lua",
		"UnitAnimal/BadTrip_Bloated_Glutch.lua",
		"UnitAnimal/BadTrip_Bloated_Glutch_Stitcher.lua",
		"UnitAnimal/PEx_Skarabei.lua",
		"UnitAnimal/PEx_Skarabei_Brute.lua",
		"UnitAnimal/Heavily_Mutated_PEx_Skarabei_Brute.lua",
		"UnitAnimal/GujoT3.lua",
		"UnitAnimal/GujoT5.lua",
		"UnitAnimal/GujoT4.lua",
		"UnitAnimal/GujoT2.lua",
		"UnitAnimal/Mutated_PEx_Skarabei_Brute.lua",
		"UnitAnimal/Shrieker_T2.lua",
	},
	'has_options', true,
	'has_data', true,
	'saved', 1778429816,
	'code_hash', -674873701780823453,
	'reapply_options_on_reload', true,
	'steam_id', "3350915173",
	'TagAnimals', true,
	'TagGameplay', true,
	'TagOther', true,
})