UndefineClass('BadTrip_Bloated_Glutch')
DefineClass.BadTrip_Bloated_Glutch = {
	__parents = { "GroundAnimal", "UnitPerkFrenzy" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	comment = "T4",
	object_class = "GroundAnimal",
	SpeciesGroup = "insects",
	UnitTags = set( "AgitatedByPheromones", "Animal" ),
	RoamRadius = 15000,
	RoamMaxDist = 7000,
	RoamIntervalMin = 4000,
	RoamIntervalMax = 8000,
	pfclass = 3,
	composite_part_groups = {
		"Glutch_Manhunting",
	},
	PainMask = "PainMask",
	SpecialOrientation = 2,
	EventProgressValue = 750,
	SightRange = 10000,
	CombatGroup = "Insects",
	HitNegationChance = {
		blunt = 5,
		energy = 35,
		gas = 85,
		pacify = 60,
		piercing = 70,
	},
	HitNegationChance_blunt = 5,
	HitNegationChance_piercing = 70,
	HitNegationChance_energy = 35,
	HitNegationChance_gas = 85,
	HitNegationChance_pacify = 60,
	HumanThreat = true,
	RobotThreat = true,
	CombatDisengageDist = 40000,
	BloodColor = 4286036179,
	max_skinned_decals_low = -1,
	FieldResearchTech = "Field_Glutch_T3",
	ObservationDistanceMin = 500,
	ObservationDistanceMax = 1500,
	lead_priority = 10,
	Icon = "UI/Icons/Resources/res_glutch_red",
	DisplayName = T(191778471383, --[[ModItemUnitAnimalCompositeDef BadTrip_Bloated_Glutch DisplayName]] "BadTrip Bloated Glutch"),
	DisplayNamePl = T(505395729353, --[[ModItemUnitAnimalCompositeDef BadTrip_Bloated_Glutch DisplayNamePl]] "BadTrip Bloated Glutch"),
	DisplayNameUnknown = T(492130038357, --[[ModItemUnitAnimalCompositeDef BadTrip_Bloated_Glutch DisplayNameUnknown]] "Unknown Glutch Evolution"),
	DisplayNameUnknownPL = T(362232721750, --[[ModItemUnitAnimalCompositeDef BadTrip_Bloated_Glutch DisplayNameUnknownPL]] "Unknown Glutch Evolution"),
	Description = T(292160509175, --[[ModItemUnitAnimalCompositeDef BadTrip_Bloated_Glutch Description]] "This species continues to grow almost exponentially. And it's outer shell continues to grow, with their death explosions causing mini-earthquakes. Dedicated firepower to pierce it like a balloon is needed. VERY resistant to gas/blunt attacks. Deals <color TextPositive>Gas</color> damage."),
	fx_actor_base_class = "Glutch",
	BaseMaxHealth = 1000000,
	FoodResources = {
		"FoodAnimalHerbivore",
		"Slop",
	},
	DailyEatingAmount = 10000,
	Diet = "Herbivore",
	EatingDuration = 5000,
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "RawMeatInsect",
			'min_amount', 30000,
			'max_amount', 40000,
		}),
	},
	SelectionRadius = 1250,
	BodySize = "small",
	DeathWeapon = "GlutchWeapon",
	CmdProduceResources = function (animal)
		return animal:DoProduceResourcesDiminishingReturns()
	end,
	AnimalPerks = {
		"AP_Regen",
		"AP_StatDamage",
		"AP_Fortified",
	},
	radius = 1500,
	movement_adjust = 1500,
	attack_weapon = "Glutch_Bad_Trip",
	IntimidationRange = 10000,
	EatStartAnim = "eat_Start",
	EatIdleAnim = {
		"eat_Idle",
	},
	EatEndAnim = "eat_End",
	anim_idle = {
		"idle",
		"idle_Active",
	},
	anim_idle_nervous = {
		"idle_Nervous",
	},
	SleepStartAnim = "sleep_Start",
	SleepIdleAnim = "sleep_Idle",
	SleepEndAnim = "sleep_End",
	SleepInterruptedAnim = "sleep_Interupted",
	MinGrownScale = 70,
	MaxGrownScale = 100,
	UnitPerkFrenzy = true,
	FrenzyHealthPct = 98,
	FrenzyEffects = {
		"Frenzy_Regen",
		"Frenzy_Conscious_3",
	},
}

