UndefineClass('Bloated_Glutch')
DefineClass.Bloated_Glutch = {
	__parents = { "GroundAnimal", "UnitPerkFrenzy" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	comment = "T3",
	object_class = "GroundAnimal",
	SpeciesGroup = "insects",
	UnitTags = set( "AgitatedByPheromones", "Animal" ),
	RoamRadius = 15000,
	RoamMaxDist = 7000,
	RoamIntervalMin = 4000,
	RoamIntervalMax = 8000,
	pfclass = 3,
	composite_part_groups = {
		"Glutch_Manhunting",
	},
	PainMask = "PainMask",
	SpecialOrientation = 2,
	EventProgressValue = 390,
	SightRange = 10000,
	CombatGroup = "Insects",
	HitNegationChance = {
		blunt = 60,
		energy = 20,
		gas = 75,
		pacify = 40,
		piercing = 5,
	},
	HitNegationChance_blunt = 60,
	HitNegationChance_piercing = 5,
	HitNegationChance_energy = 20,
	HitNegationChance_gas = 75,
	HitNegationChance_pacify = 40,
	HumanThreat = true,
	RobotThreat = true,
	CombatDisengageDist = 40000,
	BloodColor = 4286036179,
	max_skinned_decals_low = -1,
	FieldResearchTech = "FieldGlutch",
	ObservationDistanceMin = 500,
	ObservationDistanceMax = 1500,
	lead_priority = 10,
	Icon = "UI/Icons/Resources/res_glutch_red",
	DisplayName = T(379384206223, --[[ModItemUnitAnimalCompositeDef Bloated_Glutch DisplayName]] "Bloated Glutch"),
	DisplayNamePl = T(514146485774, --[[ModItemUnitAnimalCompositeDef Bloated_Glutch DisplayNamePl]] "Bloated Glutch"),
	DisplayNameUnknown = T(701919835283, --[[ModItemUnitAnimalCompositeDef Bloated_Glutch DisplayNameUnknown]] "Unknown Glutch Evolution"),
	DisplayNameUnknownPL = T(935980322975, --[[ModItemUnitAnimalCompositeDef Bloated_Glutch DisplayNameUnknownPL]] "Unknown Glutch Evolution"),
	Description = T(997698693870, --[[ModItemUnitAnimalCompositeDef Bloated_Glutch Description]] "Retaining their regenerative properties, but are immensely bulkier than their last species. Dedicated firepower to pierce it like a balloon is needed. VERY resistant to gas/blunt attacks. Deals <color TextPositive>Gas</color> damage."),
	fx_actor_base_class = "Glutch",
	BaseMaxHealth = 500000,
	FoodResources = {
		"FoodAnimalHerbivore",
		"Slop",
	},
	DailyEatingAmount = 10000,
	Diet = "Herbivore",
	EatingDuration = 5000,
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "RawMeatInsect",
			'min_amount', 30000,
			'max_amount', 40000,
		}),
	},
	SelectionRadius = 1250,
	BodySize = "small",
	DeathWeapon = "GlutchWeapon",
	CmdProduceResources = function (animal)
		return animal:DoProduceResourcesDiminishingReturns()
	end,
	AnimalPerks = {
		"AP_Regen",
	},
	radius = 1500,
	movement_adjust = 1500,
	attack_weapon = "GlutchWeapon",
	IntimidationRange = 10000,
	EatStartAnim = "eat_Start",
	EatIdleAnim = {
		"eat_Idle",
	},
	EatEndAnim = "eat_End",
	anim_idle = {
		"idle",
		"idle_Active",
	},
	anim_idle_nervous = {
		"idle_Nervous",
	},
	SleepStartAnim = "sleep_Start",
	SleepIdleAnim = "sleep_Idle",
	SleepEndAnim = "sleep_End",
	SleepInterruptedAnim = "sleep_Interupted",
	MinGrownScale = 70,
	MaxGrownScale = 100,
	UnitPerkFrenzy = true,
	FrenzyHealthPct = 99,
	FrenzyEffects = {
		"Frenzy_Regen",
		"Frenzy_Conscious_2",
	},
}

