UndefineClass('Camel_T2')
DefineClass.Camel_T2 = {
	__parents = { "UnitNesting", "CamelBase", "UnitPerkFrenzy" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	object_class = "CamelBase",
	SpeciesGroup = "species_camel",
	RoamRadius = 15000,
	RoamIntervalMin = 40000,
	RoamIntervalMax = 120000,
	composite_part_target = "CamelT2",
	composite_part_groups = {
		"Camel",
	},
	PainMask = "PainMask",
	EventProgressValue = 70,
	CombatGroup = "Camels",
	EnrageChance = 3,
	AttackMemory = 45000,
	CombatGiveUpNoHit = 30000,
	CombatFleeAccuracy = 0,
	ButcherDuration = 20000,
	max_skinned_decals_low = -2,
	FieldResearchTech = "FieldCamel",
	ObservationDistanceMin = 15000,
	ObservationDistanceMax = 20000,
	Icon = "UI/Icons/Resources/res_camel",
	DisplayName = T(860337454211, --[[ModItemUnitAnimalCompositeDef Camel_T2 DisplayName]] "Llamel"),
	DisplayNamePl = T(683878998499, --[[ModItemUnitAnimalCompositeDef Camel_T2 DisplayNamePl]] "Llamels"),
	DisplayNameUnknown = T(123371203784, --[[ModItemUnitAnimalCompositeDef Camel_T2 DisplayNameUnknown]] "Unknown Dromadda Evolution"),
	DisplayNameUnknownPL = T(226359582646, --[[ModItemUnitAnimalCompositeDef Camel_T2 DisplayNameUnknownPL]] "Unknown Dromadda Evolutions"),
	Description = T(710987730029, --[[ModItemUnitAnimalCompositeDef Camel_T2 Description]] "Dromadary with the ability to shoot spit from long distances away."),
	BaseMaxHealth = 150000,
	FoodResources = {
		"FoodAnimalHerbivore",
		"Slop",
	},
	DailyEatingAmount = 2000,
	Diet = "Herbivore",
	EatingDuration = 4000,
	FoodSourceClasses = {
		"ResourcePile",
		"Plant",
		"AnimalFeeder",
	},
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "RawMeat",
			'min_amount', 30000,
			'max_amount', 50000,
		}),
		PlaceObj('ButcherResAmount', {
			'resource', "LeatherRaw",
			'min_amount', 20000,
			'max_amount', 40000,
		}),
	},
	SelectionRadius = 1500,
	ChanceToBeMale = 40,
	BodySize = "large",
	ProduceResources = {
		PlaceObj('ResAmount', {
			'resource', "FuelManure",
			'amount', 20000,
		}),
	},
	ProduceResInterval = 1920000,
	CmdProduceResources = function (animal)
		return animal:DoProduceResourcesDiminishingReturns()
	end,
	AnimalPerks = {
		"ManureProducer",
		"DraftableAnimal",
	},
	pfclass_tamed = 10,
	pfclass_tamed_lead = 13,
	attack_weapon = "Camel_Spit",
	attack_weapon_alt = "CamelWeapon",
	EatStartAnim = "eat_Start",
	EatIdleAnim = {
		"eat_Idle",
	},
	EatEndAnim = "eat_End",
	anim_idle = {
		"idle",
		"idle_Active",
	},
	anim_idle_playful = {
		"idle_Playfull",
		"idle_Playfull2",
	},
	SleepStartAnim = "sleep_Start",
	SleepIdleAnim = "sleep_Idle",
	SleepEndAnim = "sleep_End",
	Tameable = true,
	TamingFood = "CactusFruit",
	TamingFoodAmount = 20000,
	TamingMinimumSkill = 3,
	TamingChance = 70,
	TamingAggressiveChance = 10,
	TamingDistance = 10000,
	TamedLifetimeMin = 92160000,
	TamedLifetimeMax = 138240000,
	CombatSkillInitial = range(5, 6),
	BondingChance = 10,
	ReproductionType = "two sexes",
	ReproductionGroup = "Camel",
	DailyPregnancyChance = 60,
	PregnancyDuration = 4800000,
	GrowDuration = 4800000,
	NewbornClass = "Camel_T3",
	MinGrownScale = 70,
	MaxGrownScale = 85,
	FieldVisibilityCold = 75000,
	FieldVisibilityWarm = 25000,
	PlantsToEatMin = 40,
	PlantsToEatMax = 60,
	HerdMergeClass = "Camel",
	UnitNesting = true,
	UnitPerkFrenzy = true,
	FrenzyEffects = {
		"Frenzy_Conscious_1",
	},
}

