UndefineClass('Camel_t4')
DefineClass.Camel_t4 = {
	__parents = { "CamelBase", "UnitPerkFrenzy" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	object_class = "CamelBase",
	SpeciesGroup = "species_camel",
	RoamRadius = 15000,
	RoamIntervalMin = 40000,
	RoamIntervalMax = 120000,
	composite_part_target = "CamelT4",
	composite_part_groups = {
		"Camel",
	},
	PainMask = "PainMask",
	EventProgressValue = 320,
	CombatGroup = "Camels",
	HitNegationChance = {
		HitNegationChance_blunt = 5,
		HitNegationChance_energy = 60,
		HitNegationChance_gas = 5,
		HitNegationChance_pacify = 60,
		HitNegationChance_piercing = 40,
		blunt = 5,
		energy = 60,
		gas = 5,
		pacify = 60,
		piercing = 40,
	},
	HitNegationChance_blunt = 5,
	HitNegationChance_piercing = 40,
	HitNegationChance_energy = 60,
	HitNegationChance_gas = 5,
	HitNegationChance_pacify = 60,
	EnrageChance = 3,
	AttackMemory = 45000,
	CombatGiveUpNoHit = 30000,
	CombatFleeAccuracy = 0,
	ButcherDuration = 20000,
	max_skinned_decals_low = -2,
	FieldResearchTech = "FieldCamelT3",
	ObservationDistanceMin = 15000,
	ObservationDistanceMax = 20000,
	Icon = "UI/Icons/Resources/res_camel",
	DisplayName = T(465727968103, --[[ModItemUnitAnimalCompositeDef Camel_t4 DisplayName]] "Llamel Soldier"),
	DisplayNamePl = T(703972505780, --[[ModItemUnitAnimalCompositeDef Camel_t4 DisplayNamePl]] "Llamel Soldiers"),
	DisplayNameUnknown = T(959780937654, --[[ModItemUnitAnimalCompositeDef Camel_t4 DisplayNameUnknown]] "Unknown Dromadda Evolution"),
	DisplayNameUnknownPL = T(438449897644, --[[ModItemUnitAnimalCompositeDef Camel_t4 DisplayNameUnknownPL]] "Unknown Dromadda Evolutions"),
	Description = T(134587557425, --[[ModItemUnitAnimalCompositeDef Camel_t4 Description]] "Aggressive spitting dromedary, with it's saliva able to destroy any obstacle."),
	BaseMaxHealth = 600000,
	FoodResources = {
		"FoodAnimalHerbivore",
		"Slop",
	},
	DailyEatingAmount = 4000,
	Diet = "Herbivore",
	EatingDuration = 4000,
	FoodSourceClasses = {
		"ResourcePile",
		"Plant",
		"AnimalFeeder",
	},
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "RawMeat",
			'min_amount', 30000,
			'max_amount', 50000,
		}),
		PlaceObj('ButcherResAmount', {
			'resource', "LeatherRaw",
			'min_amount', 20000,
			'max_amount', 40000,
		}),
	},
	SelectionRadius = 1500,
	ChanceToBeMale = 40,
	BodySize = "large",
	ProduceResources = {
		PlaceObj('ResAmount', {
			'resource', "FuelManure",
			'amount', 20000,
		}),
	},
	ProduceResInterval = 1920000,
	CmdProduceResources = function (animal)
		return animal:DoProduceResourcesDiminishingReturns()
	end,
	AnimalPerks = {
		"ManureProducer",
		"DraftableAnimal",
	},
	pfclass_tamed = 10,
	pfclass_tamed_lead = 13,
	attack_weapon = "Camel_Spit_T2",
	attack_weapon_alt = "CamelWeapon",
	EatStartAnim = "eat_Start",
	EatIdleAnim = {
		"eat_Idle",
	},
	EatEndAnim = "eat_End",
	anim_idle = {
		"idle",
		"idle_Active",
	},
	anim_idle_playful = {
		"idle_Playfull",
		"idle_Playfull2",
	},
	SleepStartAnim = "sleep_Start",
	SleepIdleAnim = "sleep_Idle",
	SleepEndAnim = "sleep_End",
	Tameable = true,
	TamingFood = "CactusFruit",
	TamingFoodAmount = 20000,
	TamingMinimumSkill = 3,
	TamingChance = 70,
	TamingAggressiveChance = 10,
	TamingDistance = 10000,
	TamedLifetimeMin = 92160000,
	TamedLifetimeMax = 138240000,
	CombatSkillInitial = range(5, 6),
	BondingChance = 10,
	ReproductionType = "two sexes",
	ReproductionGroup = "Camel",
	DailyPregnancyChance = 80,
	PregnancyDuration = 2000000,
	GrowDuration = 2000000,
	NewbornClass = "Camel_t5",
	MinGrownScale = 70,
	MaxGrownScale = 85,
	FieldVisibilityCold = 75000,
	FieldVisibilityWarm = 25000,
	PlantsToEatMin = 40,
	PlantsToEatMax = 60,
	HerdMergeClass = "Camel",
	UnitPerkFrenzy = true,
	FrenzyEffects = {
		"Frenzy_Conscious_3",
	},
}

