UndefineClass('dog_t5')
DefineClass.dog_t5 = {
	__parents = { "DogBase", "UnitAreaEffect", "UnitPerkFrenzy" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	object_class = "DogBase",
	SpeciesGroup = "species_dogs",
	RoamRadius = 15000,
	RoamIntervalMin = 40000,
	RoamIntervalMax = 120000,
	BypassTrapsChance = 90,
	composite_part_target = "dog_T5",
	composite_part_groups = {
		"Dog_GreatDane",
	},
	PainMask = "PainMask",
	EventProgressValue = 1400,
	SightRange = 15000,
	CombatGroup = "Insects",
	CombatUseCover = true,
	HitNegationChance = {
		blunt = 30,
		energy = 30,
		gas = 30,
		pacify = 80,
		piercing = 30,
	},
	HitNegationChance_blunt = 30,
	HitNegationChance_piercing = 30,
	HitNegationChance_energy = 30,
	HitNegationChance_gas = 30,
	HitNegationChance_pacify = 80,
	EnrageChance = 5,
	AttackMemory = 45000,
	CombatGiveUpNoHit = 30000,
	CombatFleeAccuracy = 0,
	ButcherDuration = 5000,
	max_skinned_decals_low = -1,
	FieldResearchTech = "field_dog_T5",
	ObservationDistanceMin = 12000,
	ObservationDistanceMax = 18000,
	ForcedApproachPlanning = true,
	Icon = "UI/Icons/Resources/res_dog_great_dane",
	DisplayName = T(837731857481, --[[ModItemUnitAnimalCompositeDef dog_t5 DisplayName]] "Fenrir"),
	DisplayNamePl = T(957203847118, --[[ModItemUnitAnimalCompositeDef dog_t5 DisplayNamePl]] "Fenrirs"),
	DisplayNameUnknown = T(603621195429, --[[ModItemUnitAnimalCompositeDef dog_t5 DisplayNameUnknown]] "Dog's final form?"),
	DisplayNameUnknownPL = T(524587432992, --[[ModItemUnitAnimalCompositeDef dog_t5 DisplayNameUnknownPL]] "Dog's final form?"),
	Description = T(852322442181, --[[ModItemUnitAnimalCompositeDef dog_t5 Description]] "Commander of the fauna's attacks against us. Prioritize killing to weaken the rest of the horde. Deals <color TechSubtitleBlue>Piercing</color> and <color TextNegative>Energy</color> damage."),
	BaseMaxHealth = 800000,
	FoodResources = {
		"FoodAnimalCarnivore",
		"Slop",
	},
	DailyEatingAmount = 5000,
	Diet = "Carnivore",
	EatingDuration = 4000,
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "RawMeat",
			'min_amount', 10000,
			'max_amount', 30000,
		}),
		PlaceObj('ButcherResAmount', {
			'resource', "LeatherRaw",
			'min_amount', 10000,
		}),
	},
	ChanceToBeMale = 50,
	BodySize = "small",
	CmdProduceResources = function (animal)
		return animal:DoProduceResourcesDiminishingReturns()
	end,
	AnimalPerks = {
		"DraftableAnimal",
		"AP_Commander",
	},
	radius = 400,
	pfclass_tamed = 12,
	pfclass_tamed_lead = 12,
	EnrageChanceOtherAnimals = 50,
	IntimidationRange = 10000,
	EatStartAnim = "eat_Start",
	EatIdleAnim = {
		"eat_Idle",
	},
	EatEndAnim = "eat_End",
	anim_idle = {
		"idle",
		"idle_Active",
	},
	anim_idle_nervous = {
		"idle_Nervous",
	},
	anim_idle_playful = {
		"idle_Playfull",
		"idle_Playfull2",
	},
	SleepStartAnim = "sleep_Start",
	SleepIdleAnim = "sleep_Idle",
	SleepEndAnim = "sleep_End",
	Tameable = true,
	Petable = true,
	TamingFood = "DryMeat",
	TamingFoodAmount = 60000,
	TamingMinimumSkill = 9,
	TamingChance = 25,
	TamingAggressiveChance = 80,
	TamingDistance = 30000,
	TamedLifetimeMin = 138240000,
	TamedLifetimeMax = 230400000,
	CombatSkillInitial = range(5, 6),
	BondingChance = 20,
	ReproductionType = "two sexes",
	ReproductionGroup = "Dogs",
	DailyPregnancyChance = 65,
	PregnancyDuration = 1920000,
	GrowDuration = 1920000,
	MinGrownScale = 110,
	FieldVisibilityCold = 0,
	FieldVisibilityWarm = 0,
	MoveSpeedCold = 1000,
	PlantsToEatMin = 0,
	PlantsToEatMax = 0,
	GrazingChance = 3,
	HerdMergeClass = "Dog",
	UnitAreaEffect = true,
	UnitPerkFrenzy = true,
	AffectRadius = 25000,
	AffectClass = "UnitAnimal",
	Effects = {
		PlaceObj('AreaEffectHealthCondition', {
			BodyPart = "HeadBrain",
			BodyPartGroup = "WholeHead",
			HealthCond = "ILU_dog_near_strong",
			HealthCondType = "Buff",
		}),
	},
	Disabled = function (self)
		return self:IsDead() or self:IsUnconscious()
	end,
	AffectFilter = function (self, target)
		return target.CombatGroup == self.CombatGroup
			and not target:IsDead()
			and not target:IsUnconscious()
	end,
	FrenzyHealthPct = 99,
	FrenzyEffects = {
		"Frenzy_Conscious_4",
	},
}

