UndefineClass('dog_T3')
DefineClass.dog_T3 = {
	__parents = { "DogBase", "UnitAreaEffect", "UnitPerkFrenzy" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	comment = "T3",
	object_class = "DogBase",
	SpeciesGroup = "dogs",
	RoamRadius = 15000,
	RoamIntervalMin = 40000,
	RoamIntervalMax = 120000,
	BypassTrapsChance = 20,
	composite_part_target = "dog_T3",
	composite_part_groups = {
		"Dog_GreatDane",
	},
	PainMask = "PainMask",
	EventProgressValue = 350,
	SightRange = 15000,
	CombatGroup = "Insects",
	HitNegationChance = {
		blunt = 15,
		energy = 15,
		gas = 15,
		pacify = 40,
		piercing = 15,
	},
	HitNegationChance_blunt = 15,
	HitNegationChance_piercing = 15,
	HitNegationChance_energy = 15,
	HitNegationChance_gas = 15,
	HitNegationChance_pacify = 40,
	EnrageChance = 5,
	AttackMemory = 45000,
	CombatGiveUpNoHit = 30000,
	CombatFleeAccuracy = 0,
	ButcherDuration = 5000,
	max_skinned_decals_low = -1,
	FieldResearchTech = "field_dog_T3",
	ObservationDistanceMin = 12000,
	ObservationDistanceMax = 18000,
	Icon = "UI/Icons/Resources/res_dog_great_dane",
	DisplayName = T(647785845635, --[[ModItemUnitAnimalCompositeDef dog_T3 DisplayName]] "Ice Wolf"),
	DisplayNamePl = T(777411002724, --[[ModItemUnitAnimalCompositeDef dog_T3 DisplayNamePl]] "Ice Wolf"),
	DisplayNameUnknown = T(582851449580, --[[ModItemUnitAnimalCompositeDef dog_T3 DisplayNameUnknown]] "Unknown Dog Evolution"),
	DisplayNameUnknownPL = T(971026493992, --[[ModItemUnitAnimalCompositeDef dog_T3 DisplayNameUnknownPL]] "Unknown Dog Evolution"),
	Description = T(106372402741, --[[ModItemUnitAnimalCompositeDef dog_T3 Description]] "Able to dodge and weave, avoiding small arms fire. Lives with other species, assisting in hunting, tracking, or killing their enemies. Which unfortunately is us. Deals <color TechSubtitleBlue>Piercing</color> and <color TextNegative>Energy</color> damage."),
	BaseMaxHealth = 200000,
	FoodResources = {
		"FoodAnimalCarnivore",
		"Slop",
	},
	DailyEatingAmount = 5000,
	Diet = "Carnivore",
	EatingDuration = 4000,
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "RawMeat",
			'min_amount', 10000,
			'max_amount', 30000,
		}),
		PlaceObj('ButcherResAmount', {
			'resource', "LeatherRaw",
			'min_amount', 10000,
		}),
	},
	ChanceToBeMale = 50,
	BodySize = "small",
	CmdProduceResources = function (animal)
		return animal:DoProduceResourcesDiminishingReturns()
	end,
	AnimalPerks = {
		"DraftableAnimal",
		"SmartPredator",
		"AP_Commander",
	},
	radius = 400,
	pfclass_tamed = 12,
	pfclass_tamed_lead = 12,
	EnrageChanceOtherAnimals = 50,
	IntimidationRange = 10000,
	EatStartAnim = "eat_Start",
	EatIdleAnim = {
		"eat_Idle",
	},
	EatEndAnim = "eat_End",
	anim_idle = {
		"idle",
		"idle_Active",
	},
	anim_idle_nervous = {
		"idle_Nervous",
	},
	anim_idle_playful = {
		"idle_Playfull",
		"idle_Playfull2",
	},
	SleepStartAnim = "sleep_Start",
	SleepIdleAnim = "sleep_Idle",
	SleepEndAnim = "sleep_End",
	Tameable = true,
	Petable = true,
	TamingFood = "DryMeat",
	TamingFoodAmount = 30000,
	TamingMinimumSkill = 7,
	TamingChance = 50,
	TamingAggressiveChance = 20,
	TamingDistance = 10000,
	TamedLifetimeMin = 138240000,
	TamedLifetimeMax = 230400000,
	CombatSkillInitial = range(5, 6),
	BondingChance = 20,
	ReproductionType = "two sexes",
	ReproductionGroup = "Dogs",
	DailyPregnancyChance = 65,
	PregnancyDuration = 2880000,
	GrowDuration = 2880000,
	NewbornClass = "dog_T4",
	MinGrownScale = 110,
	FieldVisibilityCold = 0,
	FieldVisibilityWarm = 0,
	MoveSpeedCold = 1000,
	PlantsToEatMin = 0,
	PlantsToEatMax = 0,
	GrazingChance = 3,
	HerdMergeClass = "Dog",
	UnitAreaEffect = true,
	UnitPerkFrenzy = true,
	AffectRadius = 10000,
	AffectClass = "UnitAnimal",
	Effects = {
		PlaceObj('AreaEffectHealthCondition', {
			BodyPart = "HeadBrain",
			BodyPartGroup = "WholeHead",
			HealthCond = "ILU_dog_near_weak",
			HealthCondType = "Buff",
		}),
	},
	Disabled = function (self)
		return self:IsDead() or self:IsUnconscious()
	end,
	AffectFilter = function (self, target)
		return target.CombatGroup == self.CombatGroup
			and not target:IsDead()
			and not target:IsUnconscious()
	end,
	FrenzyHealthPct = 99,
	FrenzyEffects = {
		"Frenzy_Conscious_2",
	},
}

