UndefineClass('dragonfly_t2')
DefineClass.dragonfly_t2 = {
	__parents = { "DragonflyBase", "UnitPerkFrenzy" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	object_class = "DragonflyBase",
	SpeciesGroup = "species_dragonfly",
	RoamMinDist = 5000,
	RoamMaxDist = 40000,
	RoamIntervalMin = 4000,
	RoamIntervalMax = 10000,
	composite_part_groups = {
		"Dragonfly",
	},
	PainMask = "PainMask",
	EventProgressValue = 80,
	SightRange = 10000,
	CombatGroup = "Insects",
	HitNegationChance = {
		blunt = 0,
		energy = 0,
		gas = 0,
		pacify = 20,
		piercing = 0,
	},
	HitNegationChance_pacify = 20,
	HumanThreat = true,
	RobotThreat = true,
	EnrageChance = 5,
	BloodColor = 4286036179,
	max_skinned_decals_low = -1,
	FieldResearchTech = "FieldHummingfly",
	ObservationDistanceMin = 17000,
	ObservationDistanceMax = 21000,
	SkipTesting = true,
	Icon = "UI/Icons/Resources/res_dragonfly",
	DisplayName = T(827606296623, --[[ModItemUnitAnimalCompositeDef dragonfly_t2 DisplayName]] "Deathfly"),
	DisplayNamePl = T(740187821407, --[[ModItemUnitAnimalCompositeDef dragonfly_t2 DisplayNamePl]] "Deathfly"),
	DisplayNameUnknown = T(284440498649, --[[ModItemUnitAnimalCompositeDef dragonfly_t2 DisplayNameUnknown]] "Unknown Hummingfly Evolution"),
	DisplayNameUnknownPL = T(238166120256, --[[ModItemUnitAnimalCompositeDef dragonfly_t2 DisplayNameUnknownPL]] "Unknown Hummingfly Evolution"),
	Description = T(524852674837, --[[ModItemUnitAnimalCompositeDef dragonfly_t2 Description]] "A Hummingfly that has evolved to be able to spit their Greek Fireballs faster, named Dragonfly. Deals <color TextNegative>Energy</color> damage."),
	BaseMaxHealth = 20000,
	FoodResources = {
		"FoodAnimalHerbivore",
		"FoodAnimalCarnivore",
		"Slop",
	},
	DailyEatingAmount = 10000,
	Diet = "Omnivore",
	EatingDuration = 4000,
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "RawMeatInsect",
			'min_amount', 8000,
		}),
	},
	SelectionRadius = 1250,
	BodySize = "small",
	CmdProduceResources = function (animal)
		return animal:DoProduceResourcesDiminishingReturns()
	end,
	AnimalPerks = {
		"AP_Frenzy",
	},
	radius = 1000,
	attack_weapon = "DragonflyRanged",
	EatStartAnim = "eat_Start",
	EatIdleAnim = {
		"eat_Idle",
	},
	EatEndAnim = "eat_End",
	anim_idle = {
		"idle",
		"idle_Active",
		"idle_Active2",
	},
	anim_idle_nervous = {
		"idle_Nervous",
	},
	SleepStartAnim = "sleep_Start",
	SleepIdleAnim = "sleep_Idle",
	SleepEndAnim = "sleep_End",
	SleepInterruptedAnim = "sleep_Interupted",
	MinGrownScale = 70,
	MaxGrownScale = 90,
	FlightMinPitch = -2700,
	FlightMaxPitch = 2700,
	FlightMaxRoll = 3600,
	FlightYawRotToRoll = 150,
	FlightDecelDist = 6000,
	FlightSimHeightMax = 6000,
	FlightSimFrictionXY = 30,
	FlightSimAttract = 2000,
	FlightSimLift = 1000,
	FlightSimMaxLift = 5000,
	FlightSimWeight = 1000,
	FlightSimMinStep = 5000,
	FlightSimMaxStep = 20000,
	FlightSimDecelDist = 20000,
	FlightSimSplineErr = 1000,
	FlightSlopePenalty = 500,
	FlightMinObstacleHeight = 1050,
	UnitPerkFrenzy = true,
	FrenzyEffects = {
		"Frenzy_Conscious_1",
	},
}

