UndefineClass('Dragonfly')
DefineClass.Dragonfly = {
	__parents = { "UnitNesting", "DragonflyBase" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	__copy_group = "Dragonfly",
	object_class = "DragonflyBase",
	SpeciesGroup = "insects",
	RoamMinDist = 5000,
	RoamMaxDist = 40000,
	RoamIntervalMin = 4000,
	RoamIntervalMax = 10000,
	composite_part_groups = {
		"Dragonfly",
	},
	PainMask = "PainMask",
	EventProgressValue = 30,
	SpawnTags = set( "Minion" ),
	SightRange = 10000,
	CombatGroup = "Insects",
	EnrageChance = 5,
	BloodColor = 4286036179,
	max_skinned_decals_low = -1,
	FieldResearchTech = "FieldHummingfly",
	ObservationDistanceMin = 17000,
	ObservationDistanceMax = 21000,
	SkipTesting = true,
	Icon = "UI/Icons/Resources/res_dragonfly",
	DisplayName = T(804776132681, --[[ModItemUnitAnimalCompositeDef Dragonfly DisplayName]] "Hummingfly"),
	DisplayNamePl = T(370391487021, --[[ModItemUnitAnimalCompositeDef Dragonfly DisplayNamePl]] "Hummingflies"),
	Description = T(345549403846, --[[ModItemUnitAnimalCompositeDef Dragonfly Description]] "Usually passive. Small chance to retaliate when attacked."),
	BaseMaxHealth = 10000,
	FoodResources = {
		"FoodAnimalHerbivore",
		"FoodAnimalCarnivore",
		"Slop",
	},
	DailyEatingAmount = 10000,
	Diet = "Omnivore",
	EatingDuration = 4000,
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "RawMeatInsect",
			'min_amount', 8000,
		}),
	},
	SelectionRadius = 1250,
	BodySize = "small",
	radius = 1000,
	attack_weapon = "DragonflyRanged",
	EatStartAnim = "eat_Start",
	EatIdleAnim = {
		"eat_Idle",
	},
	EatEndAnim = "eat_End",
	anim_idle = {
		"idle",
		"idle_Active",
		"idle_Active2",
	},
	anim_idle_nervous = {
		"idle_Nervous",
	},
	SleepStartAnim = "sleep_Start",
	SleepIdleAnim = "sleep_Idle",
	SleepEndAnim = "sleep_End",
	SleepInterruptedAnim = "sleep_Interupted",
	MinGrownScale = 70,
	MaxGrownScale = 90,
	FlightMinPitch = -2700,
	FlightMaxPitch = 2700,
	FlightMaxRoll = 3600,
	FlightYawRotToRoll = 150,
	FlightDecelDist = 6000,
	FlightSimHeightMax = 6000,
	FlightSimFrictionXY = 30,
	FlightSimAttract = 2000,
	FlightSimLift = 1000,
	FlightSimMaxLift = 5000,
	FlightSimWeight = 1000,
	FlightSimMinStep = 5000,
	FlightSimMaxStep = 20000,
	FlightSimDecelDist = 20000,
	FlightSimSplineErr = 1000,
	FlightSlopePenalty = 500,
	FlightMinObstacleHeight = 1050,
	UnitNesting = true,
}

