UndefineClass('Draka_T5')
DefineClass.Draka_T5 = {
	__parents = { "UnitNesting", "DrakaBase", "UnitPerkFrenzy" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	object_class = "DrakaBase",
	SpeciesGroup = "species_draka",
	RoamRadius = 30000,
	RoamMinDist = 5000,
	RoamMaxDist = 20000,
	RoamIntervalMax = 60000,
	composite_part_groups = {
		"DrakaT5",
	},
	composite_part_parent = {
		Test = "Forehead",
	},
	composite_part_spots = {
		Forehead = "Horns",
		HornLeft = "Horns",
		HornRight = "Horns",
		Test = "Origin",
	},
	PainMask = "PainMask",
	EventProgressValue = 1600,
	CombatGroup = "Drakkas",
	HitNegationChance = {
		HitNegationChance_blunt = 50,
		HitNegationChance_energy = 50,
		HitNegationChance_gas = 10,
		HitNegationChance_pacify = 80,
		HitNegationChance_piercing = 10,
		blunt = 50,
		energy = 50,
		gas = 10,
		pacify = 80,
		piercing = 10,
	},
	HitNegationChance_blunt = 50,
	HitNegationChance_piercing = 10,
	HitNegationChance_energy = 50,
	HitNegationChance_gas = 10,
	HitNegationChance_pacify = 80,
	EnrageChance = 15,
	AttackMemory = 45000,
	CombatGiveUpNoHit = 30000,
	CombatFleeAccuracy = 0,
	ButcherDuration = 20000,
	max_skinned_decals_low = -2,
	FieldResearchTech = "FieldDraka_T5",
	ObservationDistanceMin = 15000,
	ObservationDistanceMax = 20000,
	Icon = "UI/Icons/Resources/res_draka",
	DisplayName = T(387009331496, --[[ModItemUnitAnimalCompositeDef Draka_T5 DisplayName]] "DrikaDrekaDrakka"),
	DisplayNamePl = T(518841717627, --[[ModItemUnitAnimalCompositeDef Draka_T5 DisplayNamePl]] "DrikaDrekaDrakkas"),
	Description = T(222805768873, --[[ModItemUnitAnimalCompositeDef Draka_T5 Description]] "Aggressive Evolution of the Drakka. More stability means this creature can emit louder and louder sonic booms."),
	BaseMaxHealth = 1500000,
	FoodResources = {
		"FoodAnimalHerbivore",
		"Slop",
	},
	DailyEatingAmount = 5000,
	Diet = "Herbivore",
	EatingDuration = 4000,
	FoodSourceClasses = {
		"ResourcePile",
		"Plant",
		"AnimalFeeder",
	},
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "RawMeat",
			'min_amount', 40000,
			'max_amount', 60000,
		}),
		PlaceObj('ButcherResAmount', {
			'resource', "EnergyCrystals",
			'min_amount', 10000,
			'max_amount', 20000,
		}),
	},
	SelectionRadius = 2000,
	ChanceToBeMale = 50,
	BodySize = "large",
	ProduceResources = {
		PlaceObj('ResAmount', {
			'resource', "FuelManure",
			'amount', 15000,
		}),
	},
	ProduceResInterval = 1920000,
	CmdProduceResources = function (animal)
		if not animal:IsTamed() then
			if animal:Random(100, "no produce chance") > 40 then
				return animal:DoProduceResourcesDiminishingReturns()
			end
		end
		return animal:DoProduceResources()
	end,
	AnimalPerks = {
		"ManureProducer",
		"DraftableAnimal",
		"DrakaAcoustic",
	},
	pfclass_tamed = 10,
	pfclass_tamed_lead = 13,
	EnrageChanceOtherAnimals = 50,
	EatStartAnim = "eat_Start",
	EatIdleAnim = {
		"eat_Idle",
	},
	EatEndAnim = "eat_End",
	anim_idle = {
		"idle",
		"idle_Active",
		"idle_Active2",
	},
	anim_idle_nervous = {
		"idle_Nervous",
	},
	SleepStartAnim = "sleep_Start",
	SleepIdleAnim = "sleep_Idle",
	SleepEndAnim = "sleep_End",
	SleepInterruptedAnim = "sleep_Interrupted",
	Tameable = true,
	TamingFood = "Grain",
	TamingFoodAmount = 10000,
	TamingMinimumSkill = 5,
	TamingChance = 50,
	TamingAggressiveChance = 20,
	TamingDistance = 10000,
	TamedLifetimeMin = 92160000,
	TamedLifetimeMax = 138240000,
	CombatSkillInitial = range(5, 6),
	BondingChance = 5,
	ReproductionType = "two sexes",
	ReproductionGroup = "Draka",
	DailyPregnancyChance = 65,
	PregnancyDuration = 1800000,
	GrowDuration = 1800000,
	MaxGrownScale = 100,
	FieldVisibilityCold = 30000,
	FieldVisibilityWarm = 10000,
	MoveSpeedCold = 1000,
	PlantsToEatMin = 40,
	PlantsToEatMax = 60,
	HerdMergeClass = "Draka",
	UnitNesting = true,
	UnitPerkFrenzy = true,
	FrenzyEffects = {
		"Frenzy_Conscious_4",
		"Acoustic_T4",
	},
}

