UndefineClass('Draka_T3')
DefineClass.Draka_T3 = {
	__parents = { "DrakaBase", "UnitPerkFrenzy" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	object_class = "DrakaBase",
	SpeciesGroup = "hoofed",
	RoamRadius = 30000,
	RoamMinDist = 5000,
	RoamMaxDist = 20000,
	RoamIntervalMax = 60000,
	composite_part_groups = {
		"DrakaT3",
	},
	composite_part_parent = {
		Test = "Forehead",
	},
	composite_part_spots = {
		Forehead = "Horns",
		HornLeft = "Horns",
		HornRight = "Horns",
		Test = "Origin",
	},
	PainMask = "PainMask",
	EventProgressValue = 450,
	CombatGroup = "Drakkas",
	HitNegationChance = {
		HitNegationChance_blunt = 30,
		HitNegationChance_energy = 30,
		HitNegationChance_pacify = 40,
		blunt = 30,
		energy = 30,
		pacify = 40,
	},
	HitNegationChance_blunt = 30,
	HitNegationChance_energy = 30,
	HitNegationChance_pacify = 40,
	EnrageChance = 15,
	AttackMemory = 45000,
	CombatGiveUpNoHit = 30000,
	CombatFleeAccuracy = 0,
	ButcherDuration = 20000,
	max_skinned_decals_low = -2,
	FieldResearchTech = "FieldDraka_T3",
	ObservationDistanceMin = 15000,
	ObservationDistanceMax = 20000,
	Icon = "UI/Icons/Resources/res_draka",
	DisplayName = T(384580682194, --[[ModItemUnitAnimalCompositeDef Draka_T3 DisplayName]] "DrikaDrakk"),
	DisplayNamePl = T(959449292169, --[[ModItemUnitAnimalCompositeDef Draka_T3 DisplayNamePl]] "DrikaDrakk"),
	Description = T(807758166765, --[[ModItemUnitAnimalCompositeDef Draka_T3 Description]] "Aggressive Evolution of the Drakka. Can weaponize it's acoustic outer shell."),
	BaseMaxHealth = 800000,
	FoodResources = {
		"FoodAnimalHerbivore",
		"Slop",
	},
	DailyEatingAmount = 3000,
	Diet = "Herbivore",
	EatingDuration = 4000,
	FoodSourceClasses = {
		"ResourcePile",
		"Plant",
		"AnimalFeeder",
	},
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "RawMeat",
			'min_amount', 40000,
			'max_amount', 60000,
		}),
	},
	SelectionRadius = 2000,
	ChanceToBeMale = 40,
	BodySize = "large",
	ProduceResources = {
		PlaceObj('ResAmount', {
			'resource', "FuelManure",
			'amount', 15000,
		}),
	},
	ProduceResInterval = 1920000,
	CmdProduceResources = function (animal)
		if not animal:IsTamed() then
			if animal:Random(100, "no produce chance") > 40 then
				return animal:DoProduceResourcesDiminishingReturns()
			end
		end
		return animal:DoProduceResources()
	end,
	AnimalPerks = {
		"ManureProducer",
		"DraftableAnimal",
		"DrakaAcoustic",
	},
	pfclass_tamed = 10,
	pfclass_tamed_lead = 13,
	EnrageChanceOtherAnimals = 50,
	EatStartAnim = "eat_Start",
	EatIdleAnim = {
		"eat_Idle",
	},
	EatEndAnim = "eat_End",
	anim_idle = {
		"idle",
		"idle_Active",
		"idle_Active2",
	},
	anim_idle_nervous = {
		"idle_Nervous",
	},
	SleepStartAnim = "sleep_Start",
	SleepIdleAnim = "sleep_Idle",
	SleepEndAnim = "sleep_End",
	SleepInterruptedAnim = "sleep_Interrupted",
	Tameable = true,
	TamingFood = "Grain",
	TamingFoodAmount = 10000,
	TamingMinimumSkill = 5,
	TamingChance = 50,
	TamingAggressiveChance = 20,
	TamingDistance = 10000,
	TamedLifetimeMin = 92160000,
	TamedLifetimeMax = 138240000,
	CombatSkillInitial = range(5, 6),
	BondingChance = 5,
	ReproductionType = "two sexes",
	ReproductionGroup = "Draka",
	DailyPregnancyChance = 70,
	PregnancyDuration = 2880000,
	GrowDuration = 2880000,
	NewbornClass = "Draka_T4",
	MaxGrownScale = 100,
	FieldVisibilityCold = 30000,
	FieldVisibilityWarm = 10000,
	MoveSpeedCold = 1000,
	PlantsToEatMin = 40,
	PlantsToEatMax = 60,
	HerdMergeClass = "Draka",
	UnitPerkFrenzy = true,
	FrenzyEffects = {
		"Frenzy_Conscious_2",
		"Acoustic_T2",
	},
}

