UndefineClass('Fast_Frenzied_Fortified_Bomber_Dragonfly')
DefineClass.Fast_Frenzied_Fortified_Bomber_Dragonfly = {
	__parents = { "DragonflyBase", "UnitPerkFrenzy" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	comment = "T5",
	object_class = "DragonflyBase",
	SpeciesGroup = "insects",
	RoamMinDist = 5000,
	RoamMaxDist = 40000,
	RoamIntervalMin = 4000,
	RoamIntervalMax = 10000,
	composite_part_groups = {
		"Dragonfly",
	},
	PainMask = "PainMask",
	EventProgressValue = 1377,
	SightRange = 10000,
	CombatGroup = "Insects",
	HitNegationChance = {
		blunt = 20,
		energy = 20,
		gas = 20,
		pacify = 80,
		piercing = 20,
	},
	HitNegationChance_blunt = 20,
	HitNegationChance_piercing = 20,
	HitNegationChance_energy = 20,
	HitNegationChance_gas = 20,
	HitNegationChance_pacify = 80,
	HumanThreat = true,
	RobotThreat = true,
	EnrageChance = 5,
	BloodColor = 4286036179,
	max_skinned_decals_low = -1,
	FieldResearchTech = "Field_Dragonfly_T4",
	ObservationDistanceMin = 17000,
	ObservationDistanceMax = 21000,
	SkipTesting = true,
	Icon = "UI/Icons/Resources/res_dragonfly",
	DisplayName = T(681648056390, --[[ModItemUnitAnimalCompositeDef Fast_Frenzied_Fortified_Bomber_Dragonfly DisplayName]] "Fast Frenzied Fortified Bomber Deathfly"),
	DisplayNamePl = T(417309971999, --[[ModItemUnitAnimalCompositeDef Fast_Frenzied_Fortified_Bomber_Dragonfly DisplayNamePl]] "Fast Frenzied Fortified Bomber Deathfly"),
	DisplayNameUnknown = T(633550237976, --[[ModItemUnitAnimalCompositeDef Fast_Frenzied_Fortified_Bomber_Dragonfly DisplayNameUnknown]] "Dragonfly Final Form?"),
	DisplayNameUnknownPL = T(878944531835, --[[ModItemUnitAnimalCompositeDef Fast_Frenzied_Fortified_Bomber_Dragonfly DisplayNameUnknownPL]] "Dragonfly Final Form?"),
	Description = T(940981028550, --[[ModItemUnitAnimalCompositeDef Fast_Frenzied_Fortified_Bomber_Dragonfly Description]] "Oh great, now they are fast, deal area damage, incredibly bulky.... No clear weakness either. Deals <color TextNegative>Energy</color> damage."),
	BaseMaxHealth = 160000,
	FoodResources = {
		"FoodAnimalHerbivore",
		"FoodAnimalCarnivore",
		"Slop",
	},
	DailyEatingAmount = 10000,
	Diet = "Omnivore",
	EatingDuration = 4000,
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "RawMeatInsect",
			'min_amount', 8000,
		}),
	},
	SelectionRadius = 1250,
	BodySize = "small",
	CmdProduceResources = function (animal)
		return animal:DoProduceResourcesDiminishingReturns()
	end,
	AnimalPerks = {
		"AP_Fast",
		"AP_Frenzy",
	},
	radius = 1000,
	attack_weapon = "Dragonfly_bomb",
	EatStartAnim = "eat_Start",
	EatIdleAnim = {
		"eat_Idle",
	},
	EatEndAnim = "eat_End",
	anim_idle = {
		"idle",
		"idle_Active",
		"idle_Active2",
	},
	anim_idle_nervous = {
		"idle_Nervous",
	},
	SleepStartAnim = "sleep_Start",
	SleepIdleAnim = "sleep_Idle",
	SleepEndAnim = "sleep_End",
	SleepInterruptedAnim = "sleep_Interupted",
	MinGrownScale = 70,
	MaxGrownScale = 90,
	FlightMinPitch = -2700,
	FlightMaxPitch = 2700,
	FlightMaxRoll = 3600,
	FlightYawRotToRoll = 150,
	FlightDecelDist = 6000,
	FlightSimHeightMax = 6000,
	FlightSimFrictionXY = 30,
	FlightSimAttract = 2000,
	FlightSimLift = 1000,
	FlightSimMaxLift = 5000,
	FlightSimWeight = 1000,
	FlightSimMinStep = 5000,
	FlightSimMaxStep = 20000,
	FlightSimDecelDist = 20000,
	FlightSimSplineErr = 1000,
	FlightSlopePenalty = 500,
	FlightMinObstacleHeight = 1050,
	UnitPerkFrenzy = true,
	FrenzyHealthPct = 99,
	FrenzyEffects = {
		"Frenzy_Fast",
		"Frenzy_Conscious_4",
	},
}

