UndefineClass('Glutch_Manhunting')
DefineClass.Glutch_Manhunting = {
	__parents = { "GroundAnimal" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	object_class = "GroundAnimal",
	SpeciesGroup = "insects",
	UnitTags = set( "AgitatedByPheromones", "Animal" ),
	RoamRadius = 15000,
	RoamMaxDist = 7000,
	RoamIntervalMin = 4000,
	RoamIntervalMax = 8000,
	pfclass = 3,
	composite_part_groups = {
		"Glutch_Manhunting",
	},
	PainMask = "PainMask",
	SpecialOrientation = 2,
	EventProgressValue = 50,
	SpawnDefWeight = 20,
	SpawnTags = set( "Boss" ),
	SightRange = 10000,
	CombatGroup = "Insects",
	CombatHostile = true,
	HitNegationChance = {
		gas = 50,
	},
	HitNegationChance_gas = 50,
	CombatDisengageDist = 40000,
	BloodColor = 4286036179,
	max_skinned_decals_low = -1,
	FieldResearchTech = "FieldGlutch",
	ObservationDistanceMin = 500,
	ObservationDistanceMax = 1500,
	lead_priority = 10,
	Icon = "UI/Icons/Resources/res_glutch_red",
	DisplayName = T(274894075194, --[[ModItemUnitAnimalCompositeDef Glutch_Manhunting DisplayName]] "Manhunting Glutch"),
	DisplayNamePl = T(368662550642, --[[ModItemUnitAnimalCompositeDef Glutch_Manhunting DisplayNamePl]] "Manhunting Glutches"),
	DisplayNameUnknown = T(414783125334, --[[ModItemUnitAnimalCompositeDef Glutch_Manhunting DisplayNameUnknown]] "Aggressive bloated insect"),
	DisplayNameUnknownPL = T(994549565186, --[[ModItemUnitAnimalCompositeDef Glutch_Manhunting DisplayNameUnknownPL]] "Aggressive bloated insects"),
	Description = T(552925479785, --[[ModItemUnitAnimalCompositeDef Glutch_Manhunting Description]] "This usually passive animal has gone mad."),
	fx_actor_base_class = "Glutch",
	BaseMaxHealth = 50000,
	FoodResources = {
		"FoodAnimalHerbivore",
		"Slop",
	},
	DailyEatingAmount = 10000,
	Diet = "Herbivore",
	EatingDuration = 5000,
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "RawMeatInsect",
			'min_amount', 30000,
			'max_amount', 40000,
		}),
	},
	SelectionRadius = 1250,
	BodySize = "small",
	DeathWeapon = "GlutchWeapon",
	radius = 1500,
	movement_adjust = 1500,
	attack_weapon = "GlutchWeapon",
	IntimidationRange = 10000,
	EatStartAnim = "eat_Start",
	EatIdleAnim = {
		"eat_Idle",
	},
	EatEndAnim = "eat_End",
	anim_idle = {
		"idle",
		"idle_Active",
	},
	anim_idle_nervous = {
		"idle_Nervous",
	},
	SleepStartAnim = "sleep_Start",
	SleepIdleAnim = "sleep_Idle",
	SleepEndAnim = "sleep_End",
	SleepInterruptedAnim = "sleep_Interupted",
	MinGrownScale = 70,
	MaxGrownScale = 100,
}

