UndefineClass('Gujo_T5')
DefineClass.Gujo_T5 = {
	__parents = { "GujoBase", "UnitPerkFrenzy" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	object_class = "GujoBase",
	SpeciesGroup = "species_gujo",
	RoamIntervalMin = 2000,
	RoamIntervalMax = 3000,
	composite_part_groups = {
		"Gujo",
	},
	PainMask = "PainMask",
	damage_reduction = {
		pacify = 80,
	},
	EventProgressValue = 1400,
	turn_before_sharp_move = 0,
	CombatGroup = "Gujo",
	EnrageChance = 5,
	AttackMemory = 10000,
	CombatRageTime = 10000,
	CombatGiveUpDist = 10000,
	CombatGiveUpNoHit = 10000,
	CombatDisengageDist = 10000,
	CombatFleeAccuracy = 0,
	max_skinned_decals_low = -1,
	FieldResearchTech = "FieldGujoT4",
	ObservationDistanceMin = 17000,
	ObservationDistanceMax = 21000,
	Icon = "UI/Icons/Resources/res_gujo",
	DisplayName = T(797438362363, --[[ModItemUnitAnimalCompositeDef Gujo_T5 DisplayName]] "Vengeful Dodo"),
	DisplayNamePl = T(301981042325, --[[ModItemUnitAnimalCompositeDef Gujo_T5 DisplayNamePl]] "Vengeful Dodos"),
	DisplayNameUnknown = T(654417377239, --[[ModItemUnitAnimalCompositeDef Gujo_T5 DisplayNameUnknown]] "Gujo Final Form?"),
	DisplayNameUnknownPL = T(534116871229, --[[ModItemUnitAnimalCompositeDef Gujo_T5 DisplayNameUnknownPL]] "Gujos Final Form?"),
	Description = T(103303410892, --[[ModItemUnitAnimalCompositeDef Gujo_T5 Description]] "The closest Earth equivalent to this errant evolution of the Gujo is the dodo. If the dodo was twice the size of a human, and had a razor sharp beak! Based on it's behavior, it must be very angry the Dodo went extinct on Earth and is taking it out on literally anything on this planet."),
	BaseMaxHealth = 1000000,
	FoodResources = {
		"FoodAnimalCarnivore",
		"Slop",
	},
	DailyEatingAmount = 10000,
	Diet = "Carnivore",
	EatingDuration = 4000,
	FoodSourceClasses = {
		"UnitCorpse",
		"ResourcePile",
		"AnimalFeeder",
	},
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "RawMeatPoultry",
			'min_amount', 20000,
			'max_amount', 40000,
		}),
	},
	SelectionRadius = 1250,
	ChanceToBeMale = 50,
	BodySize = "medium",
	SleepDurationMin = 480000,
	SleepDurationMax = 480000,
	SleepAttemptAfter = 240000,
	SleepAttemptBefore = 360000,
	ProduceResources = {
		PlaceObj('ResAmount', {
			'resource', "Feathers",
			'amount', 40000,
		}),
	},
	ProduceResInterval = 2880000,
	CmdProduceResources = function (animal)
		return animal:DoProduceResourcesDiminishingReturns()
	end,
	AnimalPerks = {
		"FallingFeathers",
		"DraftableAnimal",
		"AP_Frenzy",
		"AP_Regen",
	},
	radius = 700,
	collision_radius_mod = 1300,
	pfclass_tamed = 7,
	pfclass_tamed_lead = 12,
	anim_idle = {
		"idle",
		"idle_LookingAround",
		"idle_Pecking",
		"idle_SlightlyMove",
	},
	anim_idle_playful = {
		"idle_Playfull",
		"idle_Playfull2",
	},
	SleepStartAnim = "sleep_Start",
	SleepIdleAnim = "sleep_Idle",
	SleepEndAnim = "sleep_End",
	SleepInterruptedAnim = "sleep_Interrupted",
	Tameable = true,
	Petable = true,
	TamingFood = "RawMeat",
	TamingFoodAmount = 20000,
	TamingMinimumSkill = 9,
	TamingChance = 25,
	TamingAggressiveChance = 80,
	TamingDistance = 10000,
	TamedLifetimeMin = 92160000,
	TamedLifetimeMax = 138240000,
	CombatSkillInitial = range(5, 6),
	BondingChance = 5,
	ReproductionType = "two sexes",
	ReproductionGroup = "Gujo",
	DailyPregnancyChance = 65,
	PregnancyDuration = 1920000,
	GrowDuration = 1920000,
	MinGrownScale = 75,
	MaxGrownScale = 85,
	RoamRadiusStarving = 50000,
	SightRangeStarving = 40000,
	SleepMinDist = 3000,
	SleepMaxDist = 5000,
	MovementSpeedStarving = 750,
	RoamSearchRadiusMin = 3000,
	RoamSearchRadiusMax = 5000,
	UnitPerkFrenzy = true,
	FrenzyDuration = 200000,
	FrenzyEffects = {
		"Blood_FrenzyT5",
		"Frenzy_Conscious_4",
	},
}

