UndefineClass('Juno')
DefineClass.Juno = {
	__parents = { "GroundAnimal" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	comment = "base unit, T1",
	object_class = "GroundAnimal",
	SpeciesGroup = "species_juno",
	RoamRadius = 10000,
	BypassTrapsChance = 90,
	pfclass = 5,
	composite_part_groups = {
		"Juno",
	},
	PainMask = "PainMask",
	SpecialOrientation = 9,
	EventProgressValue = 250,
	SpawnDefWeight = 5,
	SpawnTags = set( "Boss" ),
	CombatGroup = "Insects",
	CombatHostile = true,
	AttackMemory = 45000,
	CombatGiveUpNoHit = 30000,
	CombatFleeAccuracy = 0,
	aim_spot = "Aim",
	ButcherDuration = 20000,
	BloodColor = 4278467654,
	max_skinned_decals_low = -1,
	FieldResearchTech = "FieldJuno",
	ObservationDistanceMin = 500,
	ObservationDistanceMax = 1500,
	lead_priority = 5,
	Icon = "UI/Icons/Resources/res_juno",
	DisplayName = T(462402603600, --[[ModItemUnitAnimalCompositeDef Juno DisplayName]] "Juno"),
	DisplayNamePl = T(886155905930, --[[ModItemUnitAnimalCompositeDef Juno DisplayNamePl]] "Junos"),
	Description = T(403495234672, --[[ModItemUnitAnimalCompositeDef Juno Description]] "Large highly-intelligent insect that moves incredibly quick, avoids traps and deals immense damage to structures."),
	BaseMaxHealth = 150000,
	FoodResources = {
		"RawMeatHuman",
		"FoodAnimalCarnivore",
		"Slop",
	},
	DailyEatingAmount = 1000,
	Diet = "Carnivore",
	EatingDuration = 4000,
	FoodSourceClasses = {
		"ResourcePile",
		"UnitCorpse",
		"AnimalFeeder",
	},
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "RawMeatInsect",
			'min_amount', 50000,
		}),
	},
	SelectionRadius = 2000,
	ChanceToBeMale = 75,
	BodySize = "large",
	ProduceResources = {
		PlaceObj('ResAmount', {
			'resource', "Stone",
			'amount', 50000,
		}),
	},
	ProduceResInterval = 1920000,
	CmdProduceResources = function (animal)
		if not animal:IsTamed() then return animal:UpdateProductionTime() end
		return animal:DoProduceResourcesDiminishingReturns()
	end,
	AnimalPerks = {
		"StoneDigger",
		"SmartPredator",
		"DraftableAnimal",
	},
	radius = 1200,
	collision_radius_mod = 1250,
	movement_adjust = 750,
	pfclass_tamed = 11,
	pfclass_tamed_lead = 14,
	EnrageChanceOtherAnimals = 100,
	attack_weapon = "JunoMelee",
	EatStartAnim = "eat_Start",
	EatIdleAnim = {
		"eat_Idle",
	},
	EatEndAnim = "eat_End",
	anim_idle = {
		"idle",
		"idle_Active",
		"idle_Active2",
	},
	anim_idle_nervous = {
		"idle_Nervous",
	},
	SleepStartAnim = "sleep_Start",
	SleepIdleAnim = "sleep_Idle",
	SleepEndAnim = "sleep_End",
	SleepInterruptedAnim = "sleep_Interrupted",
	Tameable = true,
	TamingFood = "RawMeatHuman",
	TamingFoodAmount = 10000,
	TamingMinimumSkill = 5,
	TamingChance = 70,
	TamingAggressiveChance = 20,
	TamingDistance = 10000,
	TamedLifetimeMin = 184320000,
	TamedLifetimeMax = 322560000,
	CombatSkillInitial = range(5, 6),
	BondingChance = 5,
	ReproductionType = "two sexes",
	ReproductionGroup = "Junos",
	DailyPregnancyChance = 60,
	PregnancyDuration = 4800000,
	GrowDuration = 4800000,
	NewbornClass = "Juno_Brute",
	MinGrownScale = 70,
	MaxGrownScale = 90,
}

