UndefineClass('Junoskar')
DefineClass.Junoskar = {
	__parents = { "UnitAnimal", "UnitPerkFrenzy" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	comment = "T6",
	object_class = "UnitAnimal",
	SpeciesGroup = "insects",
	RoamRadius = 10000,
	BypassTrapsChance = 80,
	pfclass = 5,
	composite_part_groups = {
		"Junoskar",
	},
	PainMask = "PainMask",
	SpecialOrientation = 9,
	EventProgressValue = 3000,
	SpawnDefWeight = 30,
	SightRange = 50000,
	CombatGroup = "Insects",
	HitNegationChance = {
		blunt = 60,
		energy = 60,
		gas = 60,
		pacify = 80,
		piercing = 60,
	},
	HitNegationChance_blunt = 60,
	HitNegationChance_piercing = 60,
	HitNegationChance_energy = 60,
	HitNegationChance_gas = 60,
	HitNegationChance_pacify = 80,
	HumanThreat = true,
	AttackMemory = 45000,
	CombatGiveUpNoHit = 30000,
	CombatFleeAccuracy = 0,
	aim_spot = "Aim",
	ButcherDuration = 160000,
	BloodColor = 4278825740,
	FieldResearchTech = "Field_Juno_T4",
	ObservationDistanceMin = 500,
	ObservationDistanceMax = 1500,
	Icon = "UI/Icons/Resources/res_juno",
	DisplayName = T(991887602972, --[[ModItemUnitAnimalCompositeDef Junoskar DisplayName]] "Junoskar"),
	DisplayNamePl = T(247114900263, --[[ModItemUnitAnimalCompositeDef Junoskar DisplayNamePl]] "Junoskar's"),
	DisplayNameUnknown = T(858159582459, --[[ModItemUnitAnimalCompositeDef Junoskar DisplayNameUnknown]] "Juno's Final Form?"),
	DisplayNameUnknownPL = T(318813125190, --[[ModItemUnitAnimalCompositeDef Junoskar DisplayNameUnknownPL]] "Juno's Final Form?"),
	Description = T(234238503968, --[[ModItemUnitAnimalCompositeDef Junoskar Description]] "It appears to be a Juno, however is much larger in size, different in color and definitely scarier. Upon closer examination these things have the most deadliest strike that can inflict a deadly poison, capable of killing a Human in seconds. Deals <color TextButton>Blunt</color> damage."),
	BaseMaxHealth = 3000000,
	FoodResources = {
		"RawMeatHuman",
		"FoodAnimalCarnivore",
		"Slop",
	},
	DailyEatingAmount = 5000,
	Diet = "Carnivore",
	EatingDuration = 4000,
	FoodSourceClasses = {
		"ResourcePile",
		"UnitCorpse",
		"AnimalFeeder",
	},
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "RawMeatInsect",
			'min_amount', 280000,
		}),
	},
	SelectionRadius = 2000,
	ChanceToBeMale = 75,
	BodySize = "large",
	ProduceResources = {
		PlaceObj('ResAmount', {
			'resource', "Ore",
			'amount', 100000,
		}),
	},
	ProduceResInterval = 1920000,
	CmdProduceResources = function (animal)
		if not animal:IsTamed() then return animal:UpdateProductionTime() end
		return animal:DoProduceResourcesDiminishingReturns()
	end,
	AnimalPerks = {
		"StoneDigger",
		"BloodFrenzy",
		"DraftableAnimal",
		"AP_Frenzy",
		"AP_Regen",
		"AP_Conc_Immune",
	},
	radius = 1200,
	movement_adjust = 750,
	pfclass_tamed = 11,
	pfclass_tamed_lead = 14,
	EnrageChanceOtherAnimals = 100,
	attack_weapon = "Junoskar",
	CombatSkill = 10,
	IntimidationRange = 25000,
	EatStartAnim = "eat_Start",
	EatIdleAnim = {
		"eat_Idle",
	},
	EatEndAnim = "eat_End",
	anim_idle = {
		"idle",
		"idle_Active",
		"idle_Active2",
	},
	anim_idle_nervous = {
		"idle_Nervous",
	},
	SleepStartAnim = "sleep_Start",
	SleepIdleAnim = "sleep_Idle",
	SleepEndAnim = "sleep_End",
	SleepInterruptedAnim = "sleep_Interrupted",
	Tameable = true,
	TamingFood = "RawMeatHuman",
	TamingFoodAmount = 10000,
	TamingMinimumSkill = 8,
	TamingChance = 25,
	TamingAggressiveChance = 30,
	TamingDistance = 20000,
	TamedLifetimeMin = 1876800000,
	TamedLifetimeMax = 4795200000,
	CombatSkillInitial = range(5, 6),
	BondingChance = 5,
	ReproductionType = "two sexes",
	ReproductionGroup = "Junoskar",
	DailyPregnancyChance = 60,
	PregnancyDuration = 1920000,
	GrowDuration = 1920000,
	NewbornClass = "Junoskar",
	MinGrownScale = 70,
	MaxGrownScale = 90,
	UnitPerkFrenzy = true,
	FrenzyHealthPct = 99,
	FrenzyEffects = {
		"JunoFrenzy",
		"Frenzy_Regen",
		"Frenzy_Conscious_Perfect",
		"Frenzy_Fast",
	},
}

