UndefineClass('Noth_T5')
DefineClass.Noth_T5 = {
	__parents = { "UlfenBase", "UnitPerkFrenzy" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	object_class = "UlfenBase",
	SpeciesGroup = "species_noth",
	RoamRadius = 15000,
	RoamIntervalMin = 40000,
	RoamIntervalMax = 120000,
	composite_part_target = "NothT5",
	composite_part_groups = {
		"Noth",
	},
	PainMask = "PainMask",
	EventProgressValue = 1500,
	SightRange = 10000,
	CombatGroup = "Noths",
	HitNegationChance = {
		HitNegationChance_energy = 70,
		HitNegationChance_pacify = 80,
		HitNegationChance_piercing = 90,
		energy = 70,
		pacify = 80,
		piercing = 90,
	},
	HitNegationChance_piercing = 90,
	HitNegationChance_energy = 70,
	HitNegationChance_pacify = 80,
	EnrageChance = 3,
	AttackMemory = 45000,
	CombatGiveUpNoHit = 30000,
	CombatFleeAccuracy = 0,
	ButcherDuration = 20000,
	max_skinned_decals_low = -1,
	FieldResearchTech = "FieldNothT5",
	ObservationDistanceMin = 15000,
	ObservationDistanceMax = 20000,
	Icon = "UI/Icons/Resources/res_noth",
	DisplayName = T(486600116398, --[[ModItemUnitAnimalCompositeDef Noth_T5 DisplayName]] "Gullinbursti"),
	DisplayNamePl = T(913171357773, --[[ModItemUnitAnimalCompositeDef Noth_T5 DisplayNamePl]] "Gullinburstis"),
	Description = T(214347615620, --[[ModItemUnitAnimalCompositeDef Noth_T5 Description]] "Metallic Flesh, aggressive demeanor, loves to headbutt. Careful!"),
	BaseMaxHealth = 2500000,
	FoodResources = {
		"FoodAnimalHerbivore",
		"Slop",
	},
	DailyEatingAmount = 5000,
	Diet = "Herbivore",
	EatingDuration = 4000,
	FoodSourceClasses = {
		"ResourcePile",
		"Plant",
		"AnimalFeeder",
	},
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "ScrapMetal",
			'min_amount', 40000,
			'max_amount', 60000,
		}),
		PlaceObj('ButcherResAmount', {
			'resource', "Metal",
			'min_amount', 10000,
			'max_amount', 30000,
		}),
	},
	SelectionRadius = 1500,
	ChanceToBeMale = 40,
	BodySize = "medium",
	ProduceResources = {
		PlaceObj('ResAmount', {
			'resource', "ScrapMetal",
			'amount', 10000,
		}),
	},
	ProduceResInterval = 960000,
	CmdProduceResources = function (animal)
		return animal:DoProduceResourcesDiminishingReturns()
	end,
	AnimalPerks = {
		"ManureProducer",
		"DraftableAnimal",
		"AP_StatDamage",
	},
	pfclass_tamed = 10,
	pfclass_tamed_lead = 13,
	attack_weapon = "Noth_T4",
	EatStartAnim = "eat_Start",
	EatIdleAnim = {
		"eat_Idle",
	},
	EatEndAnim = "eat_End",
	anim_idle = {
		"idle",
		"idle_Active",
	},
	SleepStartAnim = "sleep_Start",
	SleepIdleAnim = "sleep_Idle",
	SleepEndAnim = "sleep_End",
	Tameable = true,
	Petable = true,
	TamingFood = "Pumpkin",
	TamingFoodAmount = 10000,
	TamingMinimumSkill = 3,
	TamingChance = 70,
	TamingAggressiveChance = 10,
	TamingDistance = 10000,
	TamedLifetimeMin = 92160000,
	TamedLifetimeMax = 138240000,
	CombatSkillInitial = range(5, 6),
	BondingChance = 10,
	ReproductionType = "two sexes",
	ReproductionGroup = "Noth",
	DailyPregnancyChance = 65,
	PregnancyDuration = 1800000,
	GrowDuration = 1800000,
	FieldVisibilityCold = 75000,
	FieldVisibilityWarm = 25000,
	MoveSpeedCold = 1000,
	PlantsToEatMin = 40,
	PlantsToEatMax = 60,
	HerdMergeClass = "Noth",
	UnitPerkFrenzy = true,
	FrenzyEffects = {
		"Frenzy_Conscious_3",
	},
}

