UndefineClass('Noth')
DefineClass.Noth = {
	__parents = { "UnitNesting", "UlfenBase" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	comment = "base unit, T1",
	object_class = "UlfenBase",
	SpeciesGroup = "species_noth",
	RoamRadius = 15000,
	RoamIntervalMin = 40000,
	RoamIntervalMax = 120000,
	composite_part_target = "Noth",
	composite_part_groups = {
		"Noth",
	},
	PainMask = "PainMask",
	EventProgressValue = 50,
	SightRange = 10000,
	CombatGroup = "Noths",
	EnrageChance = 3,
	AttackMemory = 45000,
	CombatGiveUpNoHit = 30000,
	CombatFleeAccuracy = 0,
	ButcherDuration = 20000,
	max_skinned_decals_low = -1,
	FieldResearchTech = "FieldNoth",
	ObservationDistanceMin = 15000,
	ObservationDistanceMax = 20000,
	Icon = "UI/Icons/Resources/res_noth",
	DisplayName = T(890512375005, --[[ModItemUnitAnimalCompositeDef Noth DisplayName]] "Noth"),
	DisplayNamePl = T(321321661145, --[[ModItemUnitAnimalCompositeDef Noth DisplayNamePl]] "Noths"),
	Description = T(284975794180, --[[ModItemUnitAnimalCompositeDef Noth Description]] "Usually passive. Small chance to retaliate when attacked."),
	FoodResources = {
		"FoodAnimalHerbivore",
		"Slop",
	},
	DailyEatingAmount = 1000,
	Diet = "Herbivore",
	EatingDuration = 4000,
	FoodSourceClasses = {
		"ResourcePile",
		"Plant",
		"AnimalFeeder",
	},
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "RawMeat",
			'min_amount', 40000,
			'max_amount', 60000,
		}),
		PlaceObj('ButcherResAmount', {
			'resource', "LeatherRaw",
			'min_amount', 10000,
			'max_amount', 30000,
		}),
	},
	SelectionRadius = 1500,
	ChanceToBeMale = 40,
	BodySize = "medium",
	ProduceResources = {
		PlaceObj('ResAmount', {
			'resource', "FuelManure",
			'amount', 10000,
		}),
	},
	ProduceResInterval = 960000,
	CmdProduceResources = function (animal)
		return animal:DoProduceResourcesDiminishingReturns()
	end,
	AnimalPerks = {
		"ManureProducer",
	},
	pfclass_tamed = 10,
	pfclass_tamed_lead = 13,
	attack_weapon = "NothWeapon",
	EatStartAnim = "eat_Start",
	EatIdleAnim = {
		"eat_Idle",
	},
	EatEndAnim = "eat_End",
	anim_idle = {
		"idle",
		"idle_Active",
	},
	SleepStartAnim = "sleep_Start",
	SleepIdleAnim = "sleep_Idle",
	SleepEndAnim = "sleep_End",
	Tameable = true,
	Petable = true,
	TamingFood = "Pumpkin",
	TamingFoodAmount = 10000,
	TamingMinimumSkill = 3,
	TamingChance = 70,
	TamingAggressiveChance = 10,
	TamingDistance = 10000,
	TamedLifetimeMin = 92160000,
	TamedLifetimeMax = 138240000,
	BondingChance = 10,
	ReproductionType = "two sexes",
	ReproductionGroup = "Noth",
	DailyPregnancyChance = 60,
	PregnancyDuration = 4800000,
	GrowDuration = 4800000,
	NewbornClass = "Noth_T2",
	FieldVisibilityCold = 75000,
	FieldVisibilityWarm = 25000,
	MoveSpeedCold = 1000,
	PlantsToEatMin = 40,
	PlantsToEatMax = 60,
	HerdMergeClass = "Noth",
	UnitNesting = true,
}

