UndefineClass('Noth_T3')
DefineClass.Noth_T3 = {
	__parents = { "UlfenBase", "UnitPerkFrenzy" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	object_class = "UlfenBase",
	SpeciesGroup = "hoofed",
	RoamRadius = 15000,
	RoamIntervalMin = 40000,
	RoamIntervalMax = 120000,
	composite_part_target = "NothT3",
	composite_part_groups = {
		"Noth",
	},
	PainMask = "PainMask",
	EventProgressValue = 240,
	SightRange = 10000,
	CombatGroup = "Noths",
	HitNegationChance = {
		HitNegationChance_energy = 30,
		HitNegationChance_pacify = 40,
		HitNegationChance_piercing = 10,
		energy = 30,
		pacify = 40,
		piercing = 10,
	},
	HitNegationChance_piercing = 10,
	HitNegationChance_energy = 30,
	HitNegationChance_pacify = 40,
	EnrageChance = 3,
	AttackMemory = 45000,
	CombatGiveUpNoHit = 30000,
	CombatFleeAccuracy = 0,
	ButcherDuration = 20000,
	max_skinned_decals_low = -1,
	FieldResearchTech = "FieldNothT3",
	ObservationDistanceMin = 15000,
	ObservationDistanceMax = 20000,
	Icon = "UI/Icons/Resources/res_noth",
	DisplayName = T(987839064234, --[[ModItemUnitAnimalCompositeDef Noth_T3 DisplayName]] "DuNoth"),
	DisplayNamePl = T(760617251943, --[[ModItemUnitAnimalCompositeDef Noth_T3 DisplayNamePl]] "DuNoths"),
	Description = T(201444620241, --[[ModItemUnitAnimalCompositeDef Noth_T3 Description]] "With a smaller brain, but a thicker forehead plate; this creature sports a newfound love of headbutting."),
	BaseMaxHealth = 1000000,
	FoodResources = {
		"FoodAnimalHerbivore",
		"Slop",
	},
	DailyEatingAmount = 3000,
	Diet = "Herbivore",
	EatingDuration = 4000,
	FoodSourceClasses = {
		"ResourcePile",
		"Plant",
		"AnimalFeeder",
	},
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "RawMeat",
			'min_amount', 40000,
			'max_amount', 60000,
		}),
		PlaceObj('ButcherResAmount', {
			'resource', "LeatherRaw",
			'min_amount', 10000,
			'max_amount', 30000,
		}),
	},
	SelectionRadius = 1500,
	ChanceToBeMale = 40,
	BodySize = "medium",
	ProduceResources = {
		PlaceObj('ResAmount', {
			'resource', "FuelManure",
			'amount', 10000,
		}),
	},
	ProduceResInterval = 960000,
	CmdProduceResources = function (animal)
		return animal:DoProduceResourcesDiminishingReturns()
	end,
	AnimalPerks = {
		"ManureProducer",
		"DraftableAnimal",
		"AP_StatDamage",
	},
	pfclass_tamed = 10,
	pfclass_tamed_lead = 13,
	attack_weapon = "Noth_T2",
	EatStartAnim = "eat_Start",
	EatIdleAnim = {
		"eat_Idle",
	},
	EatEndAnim = "eat_End",
	anim_idle = {
		"idle",
		"idle_Active",
	},
	SleepStartAnim = "sleep_Start",
	SleepIdleAnim = "sleep_Idle",
	SleepEndAnim = "sleep_End",
	Tameable = true,
	Petable = true,
	TamingFood = "Pumpkin",
	TamingFoodAmount = 10000,
	TamingMinimumSkill = 3,
	TamingChance = 70,
	TamingAggressiveChance = 10,
	TamingDistance = 10000,
	TamedLifetimeMin = 92160000,
	TamedLifetimeMax = 138240000,
	CombatSkillInitial = range(5, 6),
	BondingChance = 10,
	ReproductionType = "two sexes",
	ReproductionGroup = "Noth",
	DailyPregnancyChance = 70,
	PregnancyDuration = 2880000,
	GrowDuration = 2880000,
	NewbornClass = "Noth_T4",
	FieldVisibilityCold = 75000,
	FieldVisibilityWarm = 25000,
	MoveSpeedCold = 1000,
	PlantsToEatMin = 40,
	PlantsToEatMax = 60,
	HerdMergeClass = "Noth",
	UnitPerkFrenzy = true,
	FrenzyEffects = {
		"Frenzy_Conscious_1",
	},
}

