UndefineClass('Scarab_T4')
DefineClass.Scarab_T4 = {
	__parents = { "GroundAnimal", "UnitPerkFrenzy" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	object_class = "GroundAnimal",
	SpeciesGroup = "species_skarabei",
	UnitTags = set( "AgitatedByPheromones", "Animal" ),
	pfclass = 4,
	composite_part_groups = {
		"Skarabei_Manhunting",
	},
	PainMask = "PainMask",
	SpecialOrientation = 1,
	EventProgressValue = 400,
	SightRange = 15000,
	CombatGroup = "Insects",
	HitNegationChance = {
		blunt = 20,
		energy = 45,
		gas = 10,
		pacify = 60,
		piercing = 70,
	},
	HitNegationChance_blunt = 20,
	HitNegationChance_piercing = 70,
	HitNegationChance_energy = 45,
	HitNegationChance_gas = 10,
	HitNegationChance_pacify = 60,
	HumanThreat = true,
	RobotThreat = true,
	DistressCallRange = 5000,
	SwitchTargetChance = 50,
	CombatRestrictPFBonus = 250000,
	CombatGiveUpNoHit = 30000,
	CombatFleeAccuracy = 0,
	CombatObstructSmart = false,
	aim_spot = "Aim",
	CorpseDecayTimeOutside = 1440000,
	CorpseDecayTimeInside = 2400000,
	CorpseDecayTimeRefrigerated = 3840000,
	ButcherDuration = 5000,
	BloodColor = 4278467654,
	max_skinned_decals = 1,
	FieldResearchTech = "Field_Skarab_T3",
	ObservationDistanceMin = 500,
	ObservationDistanceMax = 1500,
	can_lead_formation = false,
	Icon = "UI/Icons/Resources/res_skarabei",
	DisplayName = T(--[[ModItemUnitAnimalCompositeDef Scarab_T4 DisplayName]] "Mutated PEx Skarabei Brute"),
	DisplayNamePl = T(--[[ModItemUnitAnimalCompositeDef Scarab_T4 DisplayNamePl]] "Mutated PEx Skarabei Brute"),
	DisplayNameUnknown = T(647760505585, --[[ModItemUnitAnimalCompositeDef Scarab_T4 DisplayNameUnknown]] "Unknown Skarabei Evolution"),
	DisplayNameUnknownPL = T(286154528403, --[[ModItemUnitAnimalCompositeDef Scarab_T4 DisplayNameUnknownPL]] "Unknown Skarabei Evolution"),
	Description = T(669250918824, --[[ModItemUnitAnimalCompositeDef Scarab_T4 Description]] "Never thought I would be scared of a single Skarabei, but here we are. Carapace extremely resistant to pierce and energy attacks.  Deals <color TextButton>Blunt</color> and <color TextPositive>Gas</color> damage."),
	fx_actor_base_class = "Skarabei",
	BaseMaxHealth = 500000,
	FoodResources = {
		"FoodAnimalHerbivore",
		"FoodAnimalCarnivore",
		"Slop",
	},
	DailyEatingAmount = 5000,
	Diet = "Omnivore",
	EatingDuration = 10000,
	FoodSourceClasses = {
		"UnitCorpse",
		"ResourcePile",
		"Plant",
		"AnimalFeeder",
	},
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "RawMeatInsect",
			'min_amount', 5000,
		}),
	},
	can_be_stomped = true,
	Intelligent = false,
	SelectionRadius = 100,
	ChanceToBeMale = 100,
	BodySize = "small",
	CmdProduceResources = function (animal)
		return animal:DoProduceResourcesDiminishingReturns()
	end,
	AnimalPerks = {
		"AP_Fortified",
	},
	radius = 200,
	movement_adjust = 2500,
	EnrageChanceOtherAnimals = 100,
	attack_weapon = "SkarabeiWeapon_PEx",
	EatIdleAnim = {
		"eat",
	},
	anim_idle_nervous = {
		"idle_Nervous",
	},
	SleepStartAnim = "faint",
	SleepIdleAnim = "faint_Idle",
	SleepEndAnim = "faint_To_Standing",
	SleepInterruptedAnim = "faint_To_Standing",
	ReproductionType = "two sexes",
	UnitPerkFrenzy = true,
	FrenzyHealthPct = 99,
	FrenzyEffects = {
		"Frenzy_Conscious_3",
	},
}

