UndefineClass('Scissorhands_Nesting')
DefineClass.Scissorhands_Nesting = {
	__parents = { "UnitNesting", "GroundAnimal" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	comment = "base unit, T1",
	object_class = "GroundAnimal",
	SpeciesGroup = "species_scissorhand",
	UnitTags = set( "AgitatedByPheromones", "Animal" ),
	RoamRadius = 10000,
	pfclass = 5,
	composite_part_target = "Scissorhands",
	composite_part_groups = {
		"Scissorhands",
	},
	PainMask = "PainMask",
	SpecialOrientation = 2,
	EventProgressValue = 90,
	SpawnDefWeight = 10,
	SpawnTags = set( "Boss" ),
	SightRange = 25000,
	HearingRange = 2500,
	CombatGroup = "Insects",
	CombatHostile = true,
	CombatRestrictPFBonus = 50000,
	CombatGiveUpNoHit = 30000,
	CombatFleeAccuracy = 0,
	aim_spot = "Aim",
	BloodColor = 4278467654,
	max_skinned_decals_low = -1,
	FieldResearchTech = "FieldScissorhands",
	ObservationDistanceMin = 500,
	ObservationDistanceMax = 1500,
	lead_priority = 11,
	Icon = "UI/Icons/Resources/res_scissorhands",
	DisplayName = T(282850352588, --[[ModItemUnitAnimalCompositeDef Scissorhands_Nesting DisplayName]] "Scissorhands"),
	DisplayNamePl = T(855408200427, --[[ModItemUnitAnimalCompositeDef Scissorhands_Nesting DisplayNamePl]] "Scissorhands"),
	Description = T(641150827518, --[[ModItemUnitAnimalCompositeDef Scissorhands_Nesting Description]] "Large highly-intelligent insect."),
	fx_actor_base_class = "Scissorhands",
	FoodResources = {
		"FoodAnimalHerbivore",
		"FoodAnimalCarnivore",
		"Slop",
	},
	DailyEatingAmount = 10000,
	Diet = "Omnivore",
	EatingDuration = 4000,
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "RawMeatInsect",
			'min_amount', 25000,
		}),
	},
	SelectionRadius = 1500,
	ChanceToBeMale = 50,
	BodySize = "large",
	ProduceResources = {
		PlaceObj('ResAmount', {
			'resource', "Stone",
			'amount', 30000,
		}),
	},
	ProduceResInterval = 1920000,
	CmdProduceResources = function (animal)
		if not animal:IsTamed() then return animal:UpdateProductionTime() end
		return animal:DoProduceResourcesDiminishingReturns()
	end,
	AnimalPerks = {
		"StoneDigger",
		"DraftableAnimal",
	},
	radius = 1000,
	collision_radius_mod = 1200,
	pfclass_tamed = 11,
	pfclass_tamed_lead = 14,
	EnrageChanceOtherAnimals = 100,
	attack_weapon = "ScissorhandsMelee",
	EatStartAnim = "eat_Start",
	EatIdleAnim = {
		"eat_Idle",
	},
	EatEndAnim = "eat_End",
	anim_idle = {
		"idle",
		"idle_Active",
		"idle_Active2",
	},
	anim_idle_nervous = {
		"idle_Nervous",
	},
	SleepStartAnim = "sleep_Start",
	SleepIdleAnim = "sleep_Idle",
	SleepEndAnim = "sleep_End",
	SleepInterruptedAnim = "sleep_Interrupted",
	Tameable = true,
	TamingFood = "RawMeat",
	TamingFoodAmount = 10000,
	TamingMinimumSkill = 5,
	TamingChance = 50,
	TamingAggressiveChance = 20,
	TamingDistance = 10000,
	TamedLifetimeMin = 184320000,
	TamedLifetimeMax = 322560000,
	CombatSkillInitial = range(1, 3),
	BondingChance = 5,
	ReproductionType = "two sexes",
	ReproductionGroup = "Scissorhands",
	DailyPregnancyChance = 55,
	NewbornClass = "Scissorhands_Brute",
	MinGrownScale = 100,
	MaxGrownScale = 110,
	UnitNesting = true,
	CanBeNestGuardian = true,
}

