UndefineClass('Shogu_T2')
DefineClass.Shogu_T2 = {
	__parents = { "ShoguBase", "UnitPerkFrenzy" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	object_class = "ShoguBase",
	SpeciesGroup = "species_shogu",
	RoamRadius = 15000,
	RoamIntervalMin = 40000,
	RoamIntervalMax = 120000,
	composite_part_target = "ShoguT2",
	composite_part_groups = {
		"Shogu",
	},
	PainMask = "PainMask",
	EventProgressValue = 70,
	CombatGroup = "Shogu",
	HitNegationChance = {
		HitNegationChance_gas = 15,
		HitNegationChance_pacify = 20,
		HitNegationChance_piercing = 10,
		gas = 15,
		pacify = 20,
		piercing = 10,
	},
	HitNegationChance_piercing = 10,
	HitNegationChance_gas = 15,
	HitNegationChance_pacify = 20,
	EnrageChance = 25,
	AttackMemory = 45000,
	CombatGiveUpNoHit = 30000,
	CombatFleeAccuracy = 0,
	ButcherDuration = 20000,
	max_skinned_decals_low = -1,
	FieldResearchTech = "FieldShogu",
	ObservationDistanceMin = 15000,
	ObservationDistanceMax = 20000,
	Icon = "UI/Icons/Resources/res_shogu",
	DisplayName = T(887545666757, --[[ModItemUnitAnimalCompositeDef Shogu_T2 DisplayName]] "Infected Shogu"),
	DisplayNamePl = T(990957586290, --[[ModItemUnitAnimalCompositeDef Shogu_T2 DisplayNamePl]] "Infected Shogus"),
	Description = T(115355775673, --[[ModItemUnitAnimalCompositeDef Shogu_T2 Description]] "Evolution of the Shogu that is prone to disease and ill health."),
	BaseMaxHealth = 50000,
	FoodResources = {
		"FoodAnimalHerbivore",
		"FoodAnimalCarnivore",
		"Slop",
	},
	DailyEatingAmount = 2000,
	Diet = "Omnivore",
	EatingDuration = 4000,
	FoodSourceClasses = {
		"ResourcePile",
		"UnitCorpse",
		"AnimalFeeder",
		"Plant",
	},
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "RawMeat",
			'min_amount', 30000,
			'max_amount', 50000,
		}),
		PlaceObj('ButcherResAmount', {
			'resource', "LeatherRaw",
			'min_amount', 10000,
			'max_amount', 30000,
		}),
	},
	ChanceToBeMale = 40,
	BodySize = "medium",
	ProduceResources = {
		PlaceObj('ResAmount', {
			'resource', "Potato",
			'amount', 20000,
		}),
	},
	ProduceResInterval = 1920000,
	CmdProduceResources = function (animal)
		if not animal:IsTamed() then return animal:UpdateProductionTime() end
		return animal:DoProduceResourcesDiminishingReturns()
	end,
	AnimalPerks = {
		"ChewRootsDigger",
		"DraftableAnimal",
	},
	radius = 400,
	pfclass_tamed = 7,
	pfclass_tamed_lead = 12,
	EnrageChanceOtherAnimals = 75,
	EatStartAnim = "eat_Start",
	EatIdleAnim = {
		"eat_Idle",
	},
	EatEndAnim = "eat_End",
	anim_idle = {
		"idle",
		"idle_Active1",
		"idle_Active2",
	},
	anim_idle_nervous = {
		"idle_Nervous",
	},
	SleepStartAnim = "sleep_Start",
	SleepIdleAnim = "sleep_Idle",
	SleepEndAnim = "sleep_End",
	SleepStartAnim2 = "sleep_Start2",
	SleepIdleAnim2 = "sleep_Idle2",
	SleepEndAnim2 = "sleep_End2",
	Tameable = true,
	TamingFood = "Palmfruits",
	TamingFoodAmount = 20000,
	TamingMinimumSkill = 5,
	TamingChance = 50,
	TamingAggressiveChance = 50,
	TamingDistance = 10000,
	TamedLifetimeMin = 92160000,
	TamedLifetimeMax = 138240000,
	CombatSkillInitial = range(5, 6),
	BondingChance = 5,
	ReproductionType = "two sexes",
	ReproductionGroup = "Shogu",
	DailyPregnancyChance = 60,
	PregnancyDuration = 4800000,
	GrowDuration = 4800000,
	NewbornClass = "Shogu_T3",
	FieldVisibilityCold = 0,
	FieldVisibilityWarm = 0,
	MoveSpeedCold = 1000,
	PlantsToEatMin = 0,
	PlantsToEatMax = 0,
	GrazingChance = 3,
	HerdMergeClass = "Shogu",
	UnitPerkFrenzy = true,
	AffectRadius = 5000,
	AffectClass = "UnitAnimal",
	FrenzyEffects = {
		"Frenzy_Conscious_1",
		"Shogu_Fly_Swarm",
	},
}

