UndefineClass('Shogu_t4')
DefineClass.Shogu_t4 = {
	__parents = { "ShoguBase", "UnitPerkFrenzy" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	object_class = "ShoguBase",
	SpeciesGroup = "species_shogu",
	RoamRadius = 15000,
	RoamIntervalMin = 40000,
	RoamIntervalMax = 120000,
	composite_part_target = "ShoguT4",
	composite_part_groups = {
		"Shogu",
	},
	PainMask = "PainMask",
	damage_reduction = {
		energy = -30,
	},
	EventProgressValue = 320,
	CombatGroup = "Shogu",
	HitNegationChance = {
		HitNegationChance_energy = -30,
		HitNegationChance_gas = 55,
		HitNegationChance_pacify = 60,
		HitNegationChance_piercing = 40,
		energy = -30,
		gas = 55,
		pacify = 60,
		piercing = 40,
	},
	HitNegationChance_piercing = 40,
	HitNegationChance_energy = -30,
	HitNegationChance_gas = 55,
	HitNegationChance_pacify = 60,
	EnrageChance = 25,
	AttackMemory = 45000,
	CombatGiveUpNoHit = 30000,
	CombatFleeAccuracy = 0,
	ButcherDuration = 20000,
	max_skinned_decals_low = -1,
	FieldResearchTech = "FieldShoguT3",
	ObservationDistanceMin = 15000,
	ObservationDistanceMax = 20000,
	Icon = "UI/Icons/Resources/res_shogu",
	DisplayName = T(238232468743, --[[ModItemUnitAnimalCompositeDef Shogu_t4 DisplayName]] "Poxugor"),
	DisplayNamePl = T(946414543372, --[[ModItemUnitAnimalCompositeDef Shogu_t4 DisplayNamePl]] "Poxugors"),
	Description = T(702253245244, --[[ModItemUnitAnimalCompositeDef Shogu_t4 Description]] "A diseased creature seemingly only allowed to exist to spread it's poxes. Aggressively searches for food."),
	BaseMaxHealth = 50000,
	FoodResources = {
		"FoodAnimalHerbivore",
		"FoodAnimalCarnivore",
		"Slop",
	},
	DailyEatingAmount = 4000,
	Diet = "Omnivore",
	EatingDuration = 4000,
	FoodSourceClasses = {
		"ResourcePile",
		"UnitCorpse",
		"AnimalFeeder",
		"Plant",
	},
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "Slop",
			'min_amount', 30000,
			'max_amount', 50000,
		}),
		PlaceObj('ButcherResAmount', {
			'resource', "LeatherRaw",
			'min_amount', 10000,
			'max_amount', 30000,
		}),
	},
	ChanceToBeMale = 40,
	BodySize = "medium",
	ProduceResources = {
		PlaceObj('ResAmount', {
			'resource', "Potato",
			'amount', 20000,
		}),
	},
	ProduceResInterval = 1920000,
	CmdProduceResources = function (animal)
		if not animal:IsTamed() then return animal:UpdateProductionTime() end
		return animal:DoProduceResourcesDiminishingReturns()
	end,
	AnimalPerks = {
		"ChewRootsDigger",
		"DraftableAnimal",
		"AP_StatDamage",
	},
	radius = 400,
	pfclass_tamed = 7,
	pfclass_tamed_lead = 12,
	EnrageChanceOtherAnimals = 75,
	attack_weapon = "Shogu_poison",
	EatStartAnim = "eat_Start",
	EatIdleAnim = {
		"eat_Idle",
	},
	EatEndAnim = "eat_End",
	anim_idle = {
		"idle",
		"idle_Active1",
		"idle_Active2",
	},
	anim_idle_nervous = {
		"idle_Nervous",
	},
	SleepStartAnim = "sleep_Start",
	SleepIdleAnim = "sleep_Idle",
	SleepEndAnim = "sleep_End",
	SleepStartAnim2 = "sleep_Start2",
	SleepIdleAnim2 = "sleep_Idle2",
	SleepEndAnim2 = "sleep_End2",
	Tameable = true,
	TamingFood = "Palmfruits",
	TamingFoodAmount = 20000,
	TamingMinimumSkill = 5,
	TamingChance = 50,
	TamingAggressiveChance = 50,
	TamingDistance = 10000,
	TamedLifetimeMin = 92160000,
	TamedLifetimeMax = 138240000,
	CombatSkillInitial = range(5, 6),
	BondingChance = 5,
	ReproductionType = "two sexes",
	ReproductionGroup = "Shogu",
	DailyPregnancyChance = 80,
	PregnancyDuration = 2000000,
	GrowDuration = 2000000,
	NewbornClass = "Shogu_t5",
	FieldVisibilityCold = 0,
	FieldVisibilityWarm = 0,
	MoveSpeedCold = 1000,
	PlantsToEatMin = 0,
	PlantsToEatMax = 0,
	GrazingChance = 3,
	HerdMergeClass = "Shogu",
	UnitPerkFrenzy = true,
	FrenzyEffects = {
		"Shogu_Fly_Swarm",
		"Frenzy_Conscious_3",
	},
}

