UndefineClass('Shogu_T5')
DefineClass.Shogu_T5 = {
	__parents = { "ShoguBase", "UnitPerkFrenzy", "UnitReanimate" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	object_class = "ShoguBase",
	SpeciesGroup = "species_shogu",
	RoamRadius = 15000,
	RoamIntervalMin = 40000,
	RoamIntervalMax = 120000,
	composite_part_target = "ShoguT5",
	composite_part_groups = {
		"Shogu",
	},
	PainMask = "PainMask",
	damage_reduction = {
		energy = -45,
	},
	EventProgressValue = 700,
	CombatGroup = "Shogu",
	HitNegationChance = {
		HitNegationChance_energy = -45,
		HitNegationChance_gas = 70,
		HitNegationChance_pacify = 80,
		HitNegationChance_piercing = 50,
		energy = -45,
		gas = 70,
		pacify = 80,
		piercing = 50,
	},
	HitNegationChance_piercing = 50,
	HitNegationChance_energy = -45,
	HitNegationChance_gas = 70,
	HitNegationChance_pacify = 80,
	EnrageChance = 25,
	AttackMemory = 45000,
	CombatGiveUpNoHit = 30000,
	CombatFleeAccuracy = 0,
	ButcherDuration = 20000,
	max_skinned_decals_low = -1,
	FieldResearchTech = "FieldShoguT5",
	ObservationDistanceMin = 15000,
	ObservationDistanceMax = 20000,
	Icon = "UI/Icons/Resources/res_shogu",
	DisplayName = T(286973149884, --[[ModItemUnitAnimalCompositeDef Shogu_T5 DisplayName]] "Poxumagus"),
	DisplayNamePl = T(659216291714, --[[ModItemUnitAnimalCompositeDef Shogu_T5 DisplayNamePl]] "Poxumagus"),
	Description = T(392714846508, --[[ModItemUnitAnimalCompositeDef Shogu_T5 Description]] "Filled so full of parasites, it's essentially a walking corpse. Aggressively jerks around for food."),
	BaseMaxHealth = 50000,
	FoodResources = {
		"FoodAnimalHerbivore",
		"FoodAnimalCarnivore",
		"Slop",
	},
	DailyEatingAmount = 5000,
	Diet = "Omnivore",
	EatingDuration = 4000,
	FoodSourceClasses = {
		"ResourcePile",
		"UnitCorpse",
		"AnimalFeeder",
		"Plant",
	},
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "Slop",
			'min_amount', 30000,
			'max_amount', 50000,
		}),
		PlaceObj('ButcherResAmount', {
			'resource', "LeatherRaw",
			'min_amount', 10000,
			'max_amount', 30000,
		}),
	},
	ChanceToBeMale = 40,
	BodySize = "medium",
	ProduceResources = {
		PlaceObj('ResAmount', {
			'resource', "Potato",
			'amount', 20000,
		}),
	},
	ProduceResInterval = 1920000,
	CmdProduceResources = function (animal)
		if not animal:IsTamed() then return animal:UpdateProductionTime() end
		return animal:DoProduceResourcesDiminishingReturns()
	end,
	AnimalPerks = {
		"ChewRootsDigger",
		"DraftableAnimal",
		"AP_StatDamage",
	},
	radius = 400,
	pfclass_tamed = 7,
	pfclass_tamed_lead = 12,
	EnrageChanceOtherAnimals = 75,
	attack_weapon = "Shogu_poison",
	EatStartAnim = "eat_Start",
	EatIdleAnim = {
		"eat_Idle",
	},
	EatEndAnim = "eat_End",
	anim_idle = {
		"idle",
		"idle_Active1",
		"idle_Active2",
	},
	anim_idle_nervous = {
		"idle_Nervous",
	},
	SleepStartAnim = "sleep_Start",
	SleepIdleAnim = "sleep_Idle",
	SleepEndAnim = "sleep_End",
	SleepStartAnim2 = "sleep_Start2",
	SleepIdleAnim2 = "sleep_Idle2",
	SleepEndAnim2 = "sleep_End2",
	Tameable = true,
	TamingFood = "Palmfruits",
	TamingFoodAmount = 20000,
	TamingMinimumSkill = 5,
	TamingChance = 50,
	TamingAggressiveChance = 50,
	TamingDistance = 10000,
	TamedLifetimeMin = 92160000,
	TamedLifetimeMax = 138240000,
	CombatSkillInitial = range(5, 6),
	BondingChance = 5,
	ReproductionType = "two sexes",
	ReproductionGroup = "Shogu",
	DailyPregnancyChance = 65,
	PregnancyDuration = 1800000,
	GrowDuration = 1800000,
	FieldVisibilityCold = 0,
	FieldVisibilityWarm = 0,
	MoveSpeedCold = 1000,
	PlantsToEatMin = 0,
	PlantsToEatMax = 0,
	GrazingChance = 3,
	HerdMergeClass = "Shogu",
	UnitPerkFrenzy = true,
	UnitReanimate = true,
	AffectRadius = 5000,
	AffectClass = "UnitAnimal",
	Disabled = function (self)
		return self:IsDead() or self:IsUnconscious()
	end,
	AffectFilter = function (self, target)
		return (target.class == "Ulfen_T5" or target.class == "Ulfen_T4")
			and not target:IsDead()
			and not target:IsUnconscious()
	end,
	FrenzyEffects = {
		"Frenzy_Conscious_4",
		"Shogu_Fly_Swarm",
	},
	ReanimateChance = 50,
	ReanimateHealthMin = 50,
	ReanimateDelayMax = 15000,
}

