UndefineClass('Shrieker_T2')
DefineClass.Shrieker_T2 = {
	__parents = { "UnitNesting", "ShriekerBase" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	object_class = "ShriekerBase",
	SpeciesGroup = "species_shrieker",
	UnitTags = set( "AgitatedByPheromones", "Animal" ),
	RoamRadius = 10000,
	composite_part_groups = {
		"Shrieker_Manhunting",
	},
	PainMask = "PainMask",
	EventProgressValue = 45,
	SpawnDefWeight = 20,
	SpawnTags = set( "Boss" ),
	CombatGroup = "Insects",
	CombatHostile = true,
	HitNegationChance = {
		piercing = 20,
	},
	HitNegationChance_piercing = 20,
	CombatGiveUpNoHit = 30000,
	CombatFleeAccuracy = 0,
	BloodColor = 4278467654,
	max_skinned_decals = 3,
	FieldResearchTech = "FieldShrieker",
	ObservationDistanceMin = 500,
	ObservationDistanceMax = 1500,
	lead_priority = 15,
	Icon = "UI/Icons/Resources/res_shrieker",
	DisplayName = T(329148512487, --[[ModItemUnitAnimalCompositeDef Shrieker_T2 DisplayName]] "Shrieker"),
	DisplayNamePl = T(259457015709, --[[ModItemUnitAnimalCompositeDef Shrieker_T2 DisplayNamePl]] "Shriekers"),
	Description = T(873438453556, --[[ModItemUnitAnimalCompositeDef Shrieker_T2 Description]] "This semi-intelligent nesting insect shoots spikes from its tail from wide distance."),
	fx_actor_base_class = "Shrieker",
	BaseMaxHealth = 50000,
	FoodResources = {
		"FoodAnimalCarnivore",
		"Slop",
	},
	DailyEatingAmount = 1000,
	Diet = "Carnivore",
	EatingDuration = 10000,
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "RawMeatInsect",
			'min_amount', 15000,
		}),
	},
	SelectionRadius = 1100,
	ChanceToBeMale = 100,
	BodySize = "medium",
	ProduceResources = {
		PlaceObj('ResAmount', {
			'resource', "CarbonNanotubes",
			'amount', 20000,
		}),
	},
	ProduceResInterval = 1920000,
	CmdProduceResources = function (animal)
		if not animal:IsTamed() then return animal:UpdateProductionTime() end
		return animal:DoProduceResourcesDiminishingReturns()
	end,
	AnimalPerks = {
		"StoneDigger",
		"DraftableAnimal",
	},
	collision_radius_mod = 1400,
	movement_adjust = 500,
	pfclass_tamed = 11,
	pfclass_tamed_lead = 14,
	EnrageChanceOtherAnimals = 100,
	attack_weapon_alt = "ShriekerMelee",
	CombatSkill = 3,
	EatStartAnim = "eat_Start",
	EatIdleAnim = {
		"eat_Idle",
	},
	EatEndAnim = "eat_End",
	SleepStartAnim = "sleep_Start",
	SleepIdleAnim = "sleep_Idle",
	SleepEndAnim = "sleep_End",
	SleepInterruptedAnim = "sleep_Interupted",
	Tameable = true,
	TamingFood = "RawMeatPoultry",
	TamingFoodAmount = 10000,
	TamingMinimumSkill = 5,
	TamingChance = 70,
	TamingAggressiveChance = 20,
	TamingDistance = 10000,
	TamedLifetimeMin = 138240000,
	TamedLifetimeMax = 230400000,
	CombatSkillInitial = range(5, 6),
	BondingChance = 5,
	ReproductionType = "two sexes",
	ReproductionGroup = "Shriekers",
	DailyPregnancyChance = 60,
	PregnancyDuration = 4800000,
	GrowDuration = 4800000,
	NewbornClass = "Shrieker_T3",
	MinGrownScale = 90,
	MaxGrownScale = 110,
	UnitNesting = true,
}

