UndefineClass('Skarabei_Manhunting_Brute')
DefineClass.Skarabei_Manhunting_Brute = {
	__parents = { "GroundAnimal", "UnitPerkFrenzy" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	comment = "base unit, T2",
	object_class = "GroundAnimal",
	SpeciesGroup = "species_skarabei",
	UnitTags = set( "AgitatedByPheromones", "Animal" ),
	pfclass = 4,
	composite_part_groups = {
		"Skarabei_Manhunting",
	},
	PainMask = "PainMask",
	SpecialOrientation = 1,
	EventProgressValue = 120,
	SightRange = 15000,
	CombatGroup = "Insects",
	HitNegationChance = {
		blunt = 0,
		energy = 10,
		gas = 0,
		pacify = 20,
		piercing = 20,
	},
	HitNegationChance_piercing = 20,
	HitNegationChance_energy = 10,
	HitNegationChance_pacify = 20,
	HumanThreat = true,
	RobotThreat = true,
	DistressCallRange = 5000,
	SwitchTargetChance = 50,
	CombatRestrictPFBonus = 250000,
	CombatGiveUpNoHit = 30000,
	CombatFleeAccuracy = 0,
	CombatObstructSmart = false,
	aim_spot = "Aim",
	CorpseDecayTimeOutside = 1440000,
	CorpseDecayTimeInside = 2400000,
	CorpseDecayTimeRefrigerated = 3840000,
	ButcherDuration = 5000,
	BloodColor = 4278467654,
	max_skinned_decals = 1,
	FieldResearchTech = "Field_Skarab_T1",
	ObservationDistanceMin = 500,
	ObservationDistanceMax = 1500,
	can_lead_formation = false,
	Icon = "UI/Icons/Resources/res_skarabei",
	DisplayName = T(--[[ModItemUnitAnimalCompositeDef Skarabei_Manhunting_Brute DisplayName]] "PEx Skarabei"),
	DisplayNamePl = T(--[[ModItemUnitAnimalCompositeDef Skarabei_Manhunting_Brute DisplayNamePl]] "PEx Skarabei"),
	DisplayNameUnknown = T(--[[ModItemUnitAnimalCompositeDef Skarabei_Manhunting_Brute DisplayNameUnknown]] "Unknown Skarabei evolution"),
	DisplayNameUnknownPL = T(--[[ModItemUnitAnimalCompositeDef Skarabei_Manhunting_Brute DisplayNameUnknownPL]] "Unknown Skarabei evolution"),
	Description = T(881139664981, --[[ModItemUnitAnimalCompositeDef Skarabei_Manhunting_Brute Description]] "A Skarabei swarm warrior. Poisons and explodes on death. Carapace becoming resistant to pierce and energy attacks. Deals <color TextButton>Blunt</color> and <color TextPositive>Gas</color> damage."),
	fx_actor_base_class = "Skarabei",
	FoodResources = {
		"FoodAnimalHerbivore",
		"FoodAnimalCarnivore",
		"Slop",
	},
	DailyEatingAmount = 5000,
	Diet = "Omnivore",
	EatingDuration = 10000,
	FoodSourceClasses = {
		"UnitCorpse",
		"ResourcePile",
		"Plant",
		"AnimalFeeder",
	},
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "RawMeatInsect",
			'min_amount', 25000,
		}),
	},
	can_be_stomped = true,
	Intelligent = false,
	SelectionRadius = 100,
	ChanceToBeMale = 100,
	BodySize = "small",
	CmdProduceResources = function (animal)
		return animal:DoProduceResourcesDiminishingReturns()
	end,
	radius = 200,
	movement_adjust = 2500,
	EnrageChanceOtherAnimals = 100,
	attack_weapon = "SkarabeiWeapon",
	EatIdleAnim = {
		"eat",
	},
	anim_idle_nervous = {
		"idle_Nervous",
	},
	SleepStartAnim = "faint",
	SleepIdleAnim = "faint_Idle",
	SleepEndAnim = "faint_To_Standing",
	SleepInterruptedAnim = "faint_To_Standing",
	ReproductionType = "two sexes",
	UnitPerkFrenzy = true,
	FrenzyHealthPct = 99,
	FrenzyEffects = {
		"Frenzy_Conscious_1",
	},
}

