UndefineClass('Tecatli')
DefineClass.Tecatli = {
	__parents = { "TecatliBase" },
	__generated_by_class = "ModItemUnitAnimalCompositeDef",


	comment = "T1",
	object_class = "TecatliBase",
	SpeciesGroup = "hoofed",
	RoamIntervalMin = 2000,
	RoamIntervalMax = 3000,
	pfclass = 3,
	composite_part_groups = {
		"Tecatli",
	},
	PainMask = "PainMask",
	SpecialOrientation = 8,
	EventProgressValue = 40,
	CombatGroup = "Tecatli",
	EnrageChance = 5,
	CombatGiveUpNoHit = 30000,
	CombatFleeAccuracy = 0,
	max_skinned_decals_low = -2,
	FieldResearchTech = "FieldTecatli",
	ObservationDistanceMin = 17000,
	ObservationDistanceMax = 21000,
	Icon = "UI/Icons/Resources/res_tecatli",
	DisplayName = T(517233761524, --[[ModItemUnitAnimalCompositeDef Tecatli DisplayName]] "Tecatli"),
	DisplayNamePl = T(683043160191, --[[ModItemUnitAnimalCompositeDef Tecatli DisplayNamePl]] "Tecatlies"),
	Description = T(627214810685, --[[ModItemUnitAnimalCompositeDef Tecatli Description]] "Hunts during the night. Small chance to retaliate when attacked."),
	BaseMaxHealth = 50000,
	FoodResources = {
		"FoodAnimalCarnivore",
		"Slop",
		"FoodAnimalHerbivore",
	},
	DailyEatingAmount = 1000,
	Diet = "Carnivore",
	EatingDuration = 4000,
	ButcherResources = {
		PlaceObj('ButcherResAmount', {
			'resource', "RawMeat",
			'min_amount', 20000,
			'max_amount', 30000,
		}),
	},
	SelectionRadius = 2000,
	ChanceToBeMale = 33,
	BodySize = "medium",
	CmdProduceResources = function (animal)
		return animal:DoProduceResourcesDiminishingReturns()
	end,
	AnimalPerks = {
		"DraftableAnimal",
	},
	radius = 1000,
	collision_radius_mod = 1500,
	pfclass_tamed = 10,
	pfclass_tamed_lead = 13,
	attack_weapon = "TecatliWeapon",
	anim_idle = {
		"idle",
	},
	anim_idle_playful = {
		"idle_Playfull",
		"idle_Playfull2",
	},
	SleepStartAnim = "sleep_Start",
	SleepIdleAnim = "sleep_Idle",
	SleepEndAnim = "sleep_End",
	Tameable = true,
	TamingFood = "RawMeat",
	TamingFoodAmount = 20000,
	TamingMinimumSkill = 5,
	TamingChance = 70,
	TamingAggressiveChance = 50,
	TamingDistance = 10000,
	TamedLifetimeMin = 92160000,
	TamedLifetimeMax = 138240000,
	CombatSkillInitial = range(5, 6),
	BondingChance = 5,
	ReproductionType = "two sexes",
	ReproductionGroup = "Tecatli",
	DailyPregnancyChance = 60,
	PregnancyDuration = 4800000,
	GrowDuration = 4800000,
	NewbornClass = "Entombed_Tecatli",
	MinNewbornScale = 35,
	MaxNewbornScale = 35,
	MinGrownScale = 65,
	MaxGrownScale = 75,
	RoamRadiusStarving = 50000,
	SightRangeStarving = 40000,
	MovementSpeedStarving = 1250,
}

